let state=null,currentEvent=null,eventUsed=new Set(),pendingStarter=[];
function addTag(s,t){s.tags.add(t)}
function originWealth(origin){const map={'农村务农家庭':8,'县城普通家庭':22,'三线城市工薪家庭':32,'沿海小城个体户家庭':42,'省会中产家庭':58,'一线城市普通家庭':48,'富裕经商家庭':86,'知识分子家庭':55,'单亲家庭':20,'体制内家庭':50,'制造业家庭':34,'小企业主家庭':64,'高知技术家庭':70,'跨城务工家庭':16,'资源型家庭':78,'负债经营家庭':12};return map[origin]??40}
function makeState(seed){R=rng(seed);const talent=pick(talents),flaw=pick(flaws),origin=pick(origins),city=pick(cities),persona=pick(personalities),world=pick(worlds),wb=originWealth(origin);let s={seed,age:0,origin,city,persona,talent,flaw,world,int:Math.floor(35+R()*50),health:Math.floor(50+R()*45),happy:Math.floor(45+R()*40),social:Math.floor(30+R()*55),luck:Math.floor(20+R()*75),amb:Math.floor(25+R()*65),stable:Math.floor(30+R()*55),disc:Math.floor(25+R()*65),risk:Math.floor(20+R()*70),family:Math.floor(35+R()*55),money:Math.max(0,(wb-20)*260+R()*5000),income:0,edu:0,exp:0,investSkill:0,job:'未进入社会',tags:new Set([talent,flaw,persona]),log:[],alive:true,score:0,wealthPeak:0,eventsSeen:0};
 if(talent==='商业嗅觉'){s.amb+=7;s.risk+=3}if(talent==='技术直觉'||talent==='数学直觉'||talent==='学习速度快')s.int+=7;if(talent==='社交高手'||talent==='共情能力')s.social+=9;if(talent==='情绪稳定')s.happy+=8;if(talent==='极强执行力'||talent==='强专注力')s.disc+=9;if(talent==='逆风耐受')s.stable+=8;
 if(flaw==='冲动'){s.risk+=8;s.disc-=4}if(flaw==='拖延')s.disc-=10;if(flaw==='好胜')s.amb+=8;if(flaw==='消费欲强')s.stable-=8;if(flaw==='睡眠差')s.health-=7;if(flaw==='厌恶风险'){s.stable+=8;s.risk-=10}if(flaw==='过度冒险')s.risk+=14;if(flaw==='工作成瘾'){s.amb+=8;s.health-=4}if(flaw==='社交回避')s.social-=8;if(flaw==='容易焦虑')s.happy-=7;
 if(persona==='家庭主义者')s.family+=10;if(persona==='谨慎规划者'){s.disc+=8;s.stable+=6}if(persona==='自由主义者'){s.stable-=5;s.risk+=6}if(persona==='竞争型人格')s.amb+=8;if(persona==='逆向思考者')s.int+=4;
 return s;
}
function rollLife(){const seed=(Date.now()^Math.floor(Math.random()*1e9))>>>0;state=makeState(seed);eventUsed=new Set();pendingStarter=[];currentEvent=null;for(const e of startEvents){if(chance(.42))pendingStarter.push(e)}renderStart()}
function renderStart(){const s=state;$('#seedBox').textContent='SEED '+s.seed;$('#root').innerHTML=`<div class="card start"><h2>你被随机投放到了一条人生</h2><p>V2 加入了世界时代、家庭关系、自律与风险偏好。你的出生条件会改变事件池，同一个选择也会因为状态不同而得到不同结果。</p><div class="world"><b>🌍 ${s.world.name}</b><span>${s.world.desc}</span></div><div class="rollgrid">${[['出生地',s.city],['家庭',s.origin],['人格',s.persona],['天赋',s.talent],['缺陷',s.flaw],['智力',s.int],['运气',s.luck],['野心',s.amb],['自律',s.disc],['风险偏好',s.risk],['家庭关系',s.family],['初始资产',moneyFmt(s.money)]].map(([a,b])=>`<div class="roll"><label>${a}</label><strong>${b}</strong></div>`).join('')}</div><div class="start-actions"><button class="btn" onclick="rollLife()">🎲 重 Roll</button><button class="btn primary" onclick="beginLife()">开始这一生</button></div><div class="hint">V2 · 每条人生由人物 Seed + 世界状态共同决定。存档仍保存在本机浏览器。</div></div>`}
function beginLife(){renderGame();nextYear()}
function phase(age){if(age<6)return'幼年';if(age<13)return'童年';if(age<18)return'少年';if(age<25)return'青年';if(age<40)return'成长期';if(age<55)return'中年';if(age<70)return'成熟期';return'晚年'}
function yearlyEconomy(s){if(s.age>=18){if(s.income>0){let save=s.income*(.16+s.stable/320+s.disc/500);s.money+=Math.max(0,save)}else if(s.age>22&&!s.tags.has('退休'))s.money-=7000+R()*11000}if(s.tags.has('投资者')&&s.money>10000){let drift=(-.09+R()*.19)+(s.investSkill-20)/750+s.world.market;s.money*=Math.max(.6,1+drift)}if(s.tags.has('教育负债')&&s.age<35)s.money-=3000+R()*3000;if(s.tags.has('副业跑通'))s.money+=2000+R()*8000;s.wealthPeak=Math.max(s.wealthPeak,s.money);s.score=Math.round(Math.max(0,s.money)/5000+s.happy*1.8+s.health*1.5+s.exp*3+s.amb+s.family*.7+s.disc*.5)}
function normalize(s){for(const k of['health','happy','int','social','luck','amb','stable','disc','risk','family'])s[k]=clamp(s[k]);s.money=Math.max(-200000,s.money)}
function nextYear(){if(!state.alive||currentEvent)return;state.age++;yearlyEconomy(state);if(state.age>55)state.health-=R()*1.8;if(state.tags.has('健康透支'))state.health-=R()*1.2;if(state.tags.has('慢性病'))state.health-=.5+R()*.8;if(state.age>75)state.health-=1.4+R()*2;if(state.family<25&&chance(.15))state.happy-=3;normalize(state);if(state.health<=3||(state.age>65&&chance((state.age-64)/500+(30-state.health)/700))||state.age>=102){endLife();return}if(pendingStarter.length){let e=pendingStarter.find(x=>state.age>=x.min&&state.age<=x.max&&!eventUsed.has(x.id));if(e){eventUsed.add(e.id);currentEvent={...e,cat:'成长',choices:[['接受这段经历','它会成为后续人生的一部分',s=>{e.apply(s);return e.text}]]};renderGame();return}}currentEvent=chooseEvent();if(currentEvent){if(!currentEvent.repeat)eventUsed.add(currentEvent.id);renderGame()}else{addLog('这一年没有发生改变轨道的大事。','neutral');renderGame();currentEvent=null;setTimeout(()=>{if(state.alive)nextYear()},260)}}
function chooseEvent(){let candidates=events.filter(e=>state.age>=e.min&&state.age<=e.max&&(!e.cond||e.cond(state)));if(!candidates.length)return null;let wl=candidates.map(e=>[e,(eventUsed.has(e.id)&&!e.repeat?e.w*.08:e.w)]);if(chance(.18)&&state.age>12)return null;return weighted(wl)}
function choose(i){if(!currentEvent)return;const c=currentEvent.choices[i];const before={money:state.money,health:state.health,happy:state.happy,int:state.int,social:state.social,amb:state.amb,stable:state.stable,disc:state.disc,risk:state.risk,family:state.family};const result=c[2](state)||'';normalize(state);state.eventsSeen++;const changes=[],map={money:'财富',health:'健康',happy:'幸福',int:'智力',social:'社交',amb:'野心',stable:'稳定',disc:'自律',risk:'风险',family:'家庭'};for(const k of Object.keys(map)){let d=state[k]-before[k];if(Math.abs(d)>=1)changes.push(`${map[k]}${d>0?'+':''}${k==='money'?moneyFmt(d):Math.round(d)}`)}addLog(`<b>${currentEvent.title}</b>：${result}${changes.length?` <span class="delta ${changes.some(x=>x.includes('-'))?'minus':'plus'}">${changes.join(' · ')}</span>`:''}`);currentEvent=null;renderGame();setTimeout(()=>{if(state.alive)nextYear()},320)}
function addLog(txt,cls=''){state.log.unshift({age:state.age,txt,cls});if(state.log.length>24)state.log.pop()}