function renderGame(){const s=state;$('#seedBox').textContent='SEED '+s.seed;const hidden=[...s.tags].filter(t=>['高风险偏好','创业成功','创业失败','二次创业成功','人生重启','少年阴影','早慧','迁徙经历','互联网原住民','少年负债记忆','少年导师','家庭裂痕','杠杆教训','重大疾病史','职业巅峰','副业跑通'].includes(t));$('#root').innerHTML=`<div class="grid"><aside class="card side"><div class="profile"><div class="avatar">${s.age<18?'🧒':s.age<55?'🧑':'🧓'}</div><div><div class="name">${s.city} · ${s.persona}</div><div class="sub">${s.origin} · ${s.job}</div></div></div><div class="world mini"><b>🌍 ${s.world.name}</b></div><div class="money">${moneyFmt(s.money)}</div>${stat('健康',s.health)}${stat('幸福',s.happy)}${stat('智力',s.int)}${stat('社交',s.social)}${stat('运气',s.luck)}${stat('野心',s.amb)}${stat('稳定',s.stable)}${stat('自律',s.disc)}${stat('风险偏好',s.risk)}${stat('家庭关系',s.family)}<div class="tags">${[...s.tags].slice(0,14).map(t=>`<span class="tag">${t}</span>`).join('')}${hidden.slice(0,5).map(t=>`<span class="tag hidden">隐藏·${t}</span>`).join('')}</div><div class="controls"><button class="btn" onclick="saveLife()">保存</button><button class="btn" onclick="loadLife()">读取</button><button class="btn danger" onclick="rollLife()">重开</button></div></aside><main class="card main"><div class="hero"><div><div class="age">${s.age}<small> 岁</small></div><div class="phase">${phase(s.age)} · 资产峰值 ${moneyFmt(s.wealthPeak)} · 已经历 ${s.eventsSeen} 个重要事件</div></div><div class="score"><strong>${s.score}</strong><div>人生综合分</div></div></div>${currentEvent?renderEvent(currentEvent):`<div class="event"><div class="eyebrow">YEAR ${s.age}</div><h2>时间继续向前</h2><p>正在从你的当前状态中筛选下一件可能发生的事。</p></div>`}<div class="log"><h3>人生轨迹</h3>${s.log.map(x=>`<div class="entry"><div class="yr">${x.age} 岁</div><div class="txt">${x.txt}</div></div>`).join('')||'<div class="sub">还没有重要记录。</div>'}</div></main></div>`}
function stat(n,v){return`<div class="stat"><div class="statline"><span>${n}</span><span>${Math.round(v)}</span></div><div class="bar"><div class="fill" style="width:${clamp(v)}%"></div></div></div>`}
function renderEvent(e){return`<div class="event"><div class="eyebrow">${e.cat||'人生事件'} · ${phase(state.age)}</div><h2>${e.title}</h2><p>${e.text}</p><div class="choices">${e.choices.map((c,i)=>`<button class="choice" onclick="choose(${i})"><b>${c[0]}</b><span>${c[1]}</span></button>`).join('')}</div></div>`}
function endingType(s){if(s.money>100000000)return['资本玩家','你最终进入了财富分布极端尾部。钱已经不再是主要约束，注意力和传承成为新的问题。','0.1%'];if(s.money>50000000)return['极少数人的牌桌','你最终进入财富金字塔的极高位置。','0.4%'];if(s.money>10000000&&s.happy>65&&s.family>55)return['自由而富足','你同时保住了财富、生活质量和关系，这比单纯赚到钱更罕见。','1.0%'];if(s.tags.has('二次创业成功'))return['第二次才是答案','第一次失败没有成为结局，而成了第二次成功的学费。','1.8%'];if(s.tags.has('创业成功'))return['冒险家的复利','你的人生被几次主动承担风险的决定彻底改写。','2.8%'];if(s.tags.has('杠杆教训')&&s.money>1000000)return['从牌桌边缘回来','你曾经接近出局，但最终学会了风险的价格。','3.4%'];if(s.happy>82&&s.health>60&&s.family>65)return['关系富翁','你没有把全部人生换成数字，最后留下了很高质量的关系和生活。','4.6%'];if(s.tags.has('职业巅峰')&&s.money>2000000)return['专业主义者','长期能力积累最终让你进入职业生涯的高位。','5.2%'];if(s.stable>82&&s.money>800000)return['稳定主义者','你的一生没有太多爆炸性波动，但很少真正失控。','8.9%'];if(s.money<50000&&s.happy<45)return['被周期吞没的一生','几次关键窗口没有站在你这边，资源和选择空间越来越少。','9.8%'];if(s.money<50000)return['潮水退去以后','你没有积累太多财富，但人生仍留下了自己的结构。','13.6%'];return['多数人的一生','没有神话，也没有彻底失败。命运由大量小选择与偶然共同组成。','24.1%']}
function endLife(){state.alive=false;currentEvent=null;let[title,desc,rare]=endingType(state);$('#seedBox').textContent='SEED '+state.seed;$('#root').innerHTML=`<div class="card ending"><span class="badge">人生结局 · 稀有度 ${rare}</span><h2>${title}</h2><p>${desc}</p><div class="ending-grid"><div><span>寿命</span><strong>${state.age} 岁</strong></div><div><span>最终财富</span><strong>${moneyFmt(state.money)}</strong></div><div><span>资产峰值</span><strong>${moneyFmt(state.wealthPeak)}</strong></div><div><span>重要事件</span><strong>${state.eventsSeen}</strong></div></div><p>你出生于 <b>${state.origin}</b>，成长在 <b>${state.world.name}</b>。天赋是 <b>${state.talent}</b>，缺陷是 <b>${state.flaw}</b>。</p><div class="start-actions" style="justify-content:center"><button class="btn" onclick="replaySeed()">同 Seed 重玩</button><button class="btn primary" onclick="rollLife()">Roll 新人生</button></div></div>`}
function saveLife(){let raw={...state,world:state.world,tags:[...state.tags]};localStorage.setItem('life_sim_v2',JSON.stringify(raw));toast('已保存到本机浏览器')}
function loadLife(){let raw=localStorage.getItem('life_sim_v2');if(!raw){toast('没有找到 V2 存档');return}let o=JSON.parse(raw);o.tags=new Set(o.tags);state=o;R=rng(state.seed+state.age*997);currentEvent=null;renderGame();toast('已读取存档')}
function replaySeed(){const sd=state.seed;state=makeState(sd);eventUsed=new Set();pendingStarter=[];currentEvent=null;for(const e of startEvents){if(chance(.42))pendingStarter.push(e)}renderStart()}
function shareGame(){const url=location.href.split('#')[0];if(navigator.share){navigator.share({title:'人生随机实验室 V2',text:'来 Roll 一条完全不同的人生。',url}).catch(()=>{})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(()=>toast('链接已复制')).catch(()=>toast('请复制浏览器地址'))}else{toast('请复制浏览器地址')}}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
rollLife();