window.APP = window.APP || {};
(() => {
  const A=window.APP, L=window.LIFE;
  A.p=null; A.year=[]; A.view='game'; A.lastResult=null; A.notice=''; A.busy=false;
  A.id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
  A.job=id=>L.PROFESSIONS.find(x=>x.id===id)||L.PROFESSIONS[0];
  A.note=(s,tone='')=>{const e=document.getElementById('toast');if(!e)return;e.textContent=s;e.className='toast show '+tone;clearTimeout(A.note.t);A.note.t=setTimeout(()=>e.className='toast',2600)};
  A.clampStats=p=>Object.keys(p.stats).forEach(k=>p.stats[k]=L.clamp(Math.round(p.stats[k])));
  A.pass=(r={},p=A.p)=>{if(!r)return true;if(r.any)return r.any.some(x=>A.pass(x,p));if(r.stats&&Object.entries(r.stats).some(([k,v])=>(p.stats[k]||0)<v))return false;if(r.statsMin&&Object.entries(r.statsMin).some(([k,v])=>(p.stats[k]||0)<v))return false;if(r.statsMax&&Object.entries(r.statsMax).some(([k,v])=>(p.stats[k]??100)>v))return false;if(r.tagsAll&&r.tagsAll.some(t=>!p.tags.includes(t)))return false;if(r.tagsAny&&!r.tagsAny.some(t=>p.tags.includes(t)))return false;if(r.noTags&&r.noTags.some(t=>p.tags.includes(t)))return false;if(r.wealthMin!=null&&p.wealth<r.wealthMin)return false;if(r.wealthMax!=null&&p.wealth>r.wealthMax)return false;if(r.professionMin!=null&&A.job(p.career).tier<r.professionMin)return false;if(r.childrenMin!=null&&p.children.length<r.childrenMin)return false;if(r.childrenMax!=null&&p.children.length>r.childrenMax)return false;if(r.generationMin!=null&&p.generation<r.generationMin)return false;return true};
  A.req=r=>{if(!r)return'';let a=[];if(r.stats)Object.entries(r.stats).forEach(([k,v])=>a.push(`${L.ATTR[k]?.name||k}≥${v}`));if(r.tagsAll)a.push(r.tagsAll.join('+'));if(r.tagsAny)a.push(r.tagsAny.join('/'));if(r.wealthMin!=null)a.push(`财富≥${L.fmtMoney(r.wealthMin)}`);if(r.professionMin!=null)a.push(`职业阶级≥${r.professionMin}`);return a.join(' · ')};

  A.collection=()=>{try{return JSON.parse(localStorage.getItem(L.COLLECTION_KEY))||{traits:[],endings:[],bestScore:0,bestWealth:0,runs:0}}catch{return{traits:[],endings:[],bestScore:0,bestWealth:0,runs:0}}};
  A.saveCollection=c=>localStorage.setItem(L.COLLECTION_KEY,JSON.stringify(c));
  A.discoverTrait=t=>{let c=A.collection();if(!c.traits.includes(t.id))c.traits.push(t.id);A.saveCollection(c)};
  A.discoverEnding=id=>{let c=A.collection();if(!c.endings.includes(id))c.endings.push(id);A.saveCollection(c)};

  A.traitByName=n=>L.TRAITS.find(x=>x.name===n);
  A.weightPick=arr=>{let sum=arr.reduce((s,x)=>s+(x._w??x.weight??1),0),r=Math.random()*sum;for(const x of arr){r-=(x._w??x.weight??1);if(r<=0)return x}return arr[arr.length-1]};
  A.rollTraits=n=>{let pool=[...L.TRAITS],out=[];while(out.length<n&&pool.length){let t=A.weightPick(pool.map(x=>({...x,_w:L.RARITY[x.rarity].weight})));out.push(L.TRAITS.find(x=>x.id===t.id));pool=pool.filter(x=>x.id!==t.id)}return out};
  A.acquireTrait=t=>{if(!t||A.p.traits.some(x=>x.id===t.id))return null;A.p.traits.push({id:t.id,name:t.name,rarity:t.rarity});Object.entries(t.effects||{}).forEach(([k,v])=>{if(k in A.p.stats)A.p.stats[k]+=v});A.clampStats(A.p);A.discoverTrait(t);return t};
  A.traitMods=()=>{let m={success:0,rare:0,death:1,recovery:0,income:0,wealthOutcome:0,spouse:0,badGuard:0,comeback:0};for(const ref of A.p.traits||[]){let t=L.TRAITS.find(x=>x.id===ref.id);if(!t)continue;for(const[k,v]of Object.entries(t.mods||{})){if(k==='death')m.death*=v;else m[k]=(m[k]||0)+v}}return m};
  A.setCounts=()=>{let c={};Object.keys(L.SYNERGY_SETS).forEach(k=>c[k]=0);for(const ref of A.p.traits||[]){let t=L.TRAITS.find(x=>x.id===ref.id);(t?.sets||[]).forEach(s=>c[s]=(c[s]||0)+1)}return c};
  A.setTier=(key,counts=A.setCounts())=>{let n=counts[key]||0,t=0;for(const x of L.SYNERGY_SETS[key].tiers)if(n>=x)t++;return t};
  A.synergyMods=()=>{let c=A.setCounts(),m={success:0,rare:0,death:1,income:0,spouse:0,extreme:0};let t=A.setTier('wealth',c);m.income+=[0,.05,.12,.22][t];t=A.setTier('mind',c);m.success+=[0,.05,.12,.20][t];t=A.setTier('social',c);m.spouse+=[0,.08,.17,.30][t];t=A.setTier('body',c);m.death*=[1,.90,.75,.60][t];t=A.setTier('family',c);m.spouse+=[0,.06,.14,.25][t];t=A.setTier('creative',c);m.rare+=[0,.04,.10,.20][t];t=A.setTier('fortune',c);m.rare+=[0,.05,.12,.22][t];t=A.setTier('risk',c);m.extreme+=[0,.08,.18,.32][t];return m};

  A.draft=()=>{let b=L.pick(L.BACKGROUNDS),pe=L.pick(L.PERSONALITIES),ta=L.pick(L.TALENTS),f=L.pick(L.FLAWS),w=L.pick(L.WORLDS),stats={health:L.rand(45,72),happiness:L.rand(44,72),intelligence:L.rand(42,72),social:L.rand(38,70),luck:L.rand(32,74),ambition:L.rand(38,72),stability:L.rand(40,72),discipline:L.rand(38,72),risk:L.rand(28,72),family:b[2]};[pe[1],ta[1],f[1]].forEach(e=>Object.entries(e).forEach(([k,v])=>stats[k]=L.clamp((stats[k]||50)+v)));return{b,pe,ta,f,w,stats,traits:A.rollTraits(5),avatar:L.rand(0,L.AVATARS.length-1),wealth:Math.max(0,b[1]*1000+L.rand(-12000,22000))}};
  A.newLife=d=>{A.p={id:A.id(),name:'你',avatar:d.avatar,age:1,seed:L.rand(100000000,999999999),world:d.w,background:d.b[0],personality:d.pe[0],talent:d.ta[0],flaw:d.f[0],stats:{...d.stats},traits:[],tags:[d.pe[0],d.ta[0],d.f[0],d.b[3]].filter(Boolean),wealth:d.wealth,wealthPeak:d.wealth,minWealth:d.wealth,career:'none',careerTierPeak:0,salaryMul:1,education:'未定',graduationAge:null,spouse:null,children:[],history:[],seen:{},generation:1,parentId:null,alive:true,deathReason:'',score:0,rareEvents:0,positive:0,negative:0,neutral:0};for(const t of d.traits)A.acquireTrait(t);A.p.history.unshift({age:0,title:'🎲 开局词条',text:d.traits.map(x=>x.name).join(' · '),changes:'',tone:'neutral',kind:'start'});A.syncDynasty();A.save();A.buildYear();};

  A.dynasty=()=>{try{return JSON.parse(localStorage.getItem(L.DYNASTY_KEY))||{members:[]}}catch{return{members:[]}}};
  A.saveDyn=d=>localStorage.setItem(L.DYNASTY_KEY,JSON.stringify(d));
  A.syncDynasty=()=>{let p=A.p,d=A.dynasty(),m=d.members.find(x=>x.id===p.id);if(!m){m={id:p.id,parentId:p.parentId,generation:p.generation,children:[]};d.members.push(m)}Object.assign(m,{name:p.name,avatar:p.avatar,status:p.alive?'在世':'已故',career:A.job(p.career).name,wealth:p.wealth,age:p.age,children:p.children.map(x=>x.id)});A.saveDyn(d)};
  A.spouse=()=>{if(A.p.spouse)return;A.p.spouse={id:A.id(),name:L.pick(['林澈','沈宁','周野','顾遥','许岚','陈川','苏梨','陆森','夏霁','程砚','唐绫','江燃']),trait:L.pick(['温和务实','野心勃勃','松弛乐观','理性克制','社交达人','独立敏锐']),avatar:L.rand(0,L.AVATARS.length-1),since:A.p.age};};
  A.child=()=>{if(A.p.children.length>=3)return null;let c={id:A.id(),name:L.pick(['小舟','小满','星禾','知夏','一川','青岚','向野','安宁','予澈','明川'])+(A.p.children.length?A.p.children.length+1:''),avatar:L.rand(0,L.AVATARS.length-1),birthAge:A.p.age,generation:A.p.generation+1};A.p.children.push(c);return c};
  A.setJob=id=>{['上班族','管理者','技术专家','创业者','创业成功','技能型','内容创作者'].forEach(t=>A.p.tags=A.p.tags.filter(x=>x!==t));A.p.career=id;let j=A.job(id);(j.tags||[]).forEach(t=>{if(!A.p.tags.includes(t))A.p.tags.push(t)});A.p.careerTierPeak=Math.max(A.p.careerTierPeak,j.tier||0)};
  A.special=s=>{if(!s)return;let p=A.p;if(s.wealth)p.wealth+=s.wealth;if(s.career)A.setJob(s.career);if(s.createSpouse)A.spouse();if(s.marry){A.spouse();if(!p.tags.includes('已婚'))p.tags.push('已婚');p.tags=p.tags.filter(x=>x!=='恋爱中')}if(s.clearSpouse){p.spouse=null;p.tags=p.tags.filter(x=>x!=='已婚');if(!p.tags.includes('已离婚'))p.tags.push('已离婚')}if(s.haveChild)A.child();if(s.education)p.education=s.education;if(s.graduationAge)p.graduationAge=s.graduationAge;if(s.maritalPlan){p.maritalPlan=s.maritalPlan}if(s.addTag&&!p.tags.includes(s.addTag))p.tags.push(s.addTag);if(s.removeTag)p.tags=p.tags.filter(x=>x!==s.removeTag);if(s.blockInvestment){p.blockedInvestment=true;p.tags=p.tags.filter(x=>x!=='投资者')}};

  A.zhouActions=()=>L.ZHOU_CHOICES.map((z,i)=>({id:'zhou15_'+i,category:'抓周',title:`${z[1]} ${z[0]}`,desc:`可能获得：${z[2].join(' / ')}`,effects:z[3],special:{grantZhou:z[2]},fixed:true,rare:true,previewTraits:z[2]}));
  A.graduationActions=()=>{let p=A.p,map=p.tags.includes('医学专业')?['doctor','medtech','researcher','sales','freelancer']:p.tags.includes('警校路线')?['police','civil','sales','technician','freelancer']:p.tags.includes('数理工科')?['developer','engineer','researcher','product','freelancer']:p.tags.includes('艺术传媒')?['artist','creator','designer','sales','freelancer']:['sales','finance','lawyer','product','clerk'];return map.map(id=>({id:'grad_'+id,category:'毕业择业',title:`进入${A.job(id).name}`,desc:'第一份工作不会决定一生，但会改变后面的事件池。',effects:{ambition:2,stability:2},special:{career:id,graduated:true},fixed:true}))};
  A.fixedActions=()=>{let p=A.p;if(p.age===1)return A.zhouActions();if(p.graduationAge===p.age&&!p.tags.includes('已毕业'))return A.graduationActions();let f=L.MILESTONES?.[p.age];if(f){let x=typeof f==='function'?f(p):f;if(x&&x.length)return x}return null};

  A.eventEligible=e=>{let p=A.p;if(p.age<e.minAge||p.age>e.maxAge||!A.pass(e.requires))return false;if(e.category==='投资'&&(p.blockedInvestment||(e.id!=='start_investing'&&!p.tags.includes('投资者'))))return false;if(!e.repeatable&&p.seen[e.id]!=null)return false;if(e.repeatable&&p.seen[e.id]!=null&&p.age-p.seen[e.id]<(e.cooldown||4))return false;return true};
  A.fromEvent=e=>{let opts=(e.options||[]).filter(o=>A.pass(o.requires||{}));if(!opts.length)return null;let o=L.pick(opts);return{id:e.id,category:e.category,title:e.title,desc:o.label,sub:e.desc,requires:o.requires||{},outcomes:o.results||null,effects:o.effects||{},addTags:o.addTags||[],special:o.special||{},hidden:e.hidden,rare:e.hidden,sourceEvent:e.id,fixed:false}};
  A.fallbacks=()=>[
    {id:'fb_rest',category:'生活',title:'给自己放一个真正的假',desc:'这一年你决定少卷一点。',effects:{happiness:7,health:3,ambition:-2}},
    {id:'fb_skill',category:'成长',title:'学一门新技能',desc:'可能有用，也可能只是新的兴趣。',effects:{intelligence:5,discipline:3,happiness:-1}},
    {id:'fb_network',category:'社交',title:'主动认识新圈子',desc:'把自己放进陌生人里。',effects:{social:6,happiness:2,stability:-2}},
    {id:'fb_save',category:'财富',title:'把现金流收紧一年',desc:'少花钱，多留安全垫。',effects:{stability:6,happiness:-3},special:{wealth:18000}},
    {id:'fb_trip',category:'生活',title:'去一个没去过的地方',desc:'花钱换一次新鲜感。',effects:{happiness:7,social:3},special:{wealth:-12000}},
    {id:'fb_push',category:'职业',title:'主动接一个难项目',desc:'可能升得快，也可能被压力反噬。',effects:{ambition:6,discipline:3,health:-3}},
    {id:'fb_family',category:'家庭',title:'认真陪家人一段时间',desc:'时间不能存起来，但关系会记账。',effects:{family:8,happiness:4,ambition:-2}},
    {id:'fb_side',category:'副业',title:'试一个小副业',desc:'不赌身家，只测试市场。',effects:{ambition:5,discipline:3},special:{wealth:-5000}},
    {id:'fb_sport',category:'健康',title:'重新开始运动',desc:'前几周很痛苦，后面可能上瘾。',effects:{health:7,discipline:3,happiness:2}},
    {id:'fb_decline',category:'生活',title:'拒绝一些没必要的事',desc:'守住边界，也会错过少量关系。',effects:{stability:6,social:-2,happiness:3}}
  ];
  A.buildYear=()=>{let p=A.p;if(!p||!p.alive)return A.render?.();A.notice='';let fixed=A.fixedActions();if(fixed){A.year=fixed;return A.render?.()}let pool=L.EVENTS.filter(A.eventEligible),picked=[],used=new Set();while(picked.length<5&&pool.length){let e=A.weightPick(pool.map(x=>({...x,_w:(x.weight||1)*(x.hidden?1+Math.max(0,p.stats.luck-50)/70:1)})));pool=pool.filter(x=>x.id!==e.id);let a=A.fromEvent(e);if(a&&!used.has(a.id)){picked.push(a);used.add(a.id)}}for(const f of A.fallbacks().sort(()=>Math.random()-.5)){if(picked.length>=5)break;if(!used.has(f.id)){picked.push(f);used.add(f.id)}}A.year=picked.slice(0,5);A.render?.()};

  A.outcomeScore=o=>{let s=0;Object.values(o.effects||{}).forEach(v=>s+=v);let w=o.special?.wealth||0;s+=Math.max(-20,Math.min(20,w/15000));if(o.good)s+=8;return s};
  A.pickOutcome=outcomes=>{let p=A.p,tm=A.traitMods(),sm=A.synergyMods(),luck=(p.stats.luck-50)/50;let low=p.wealth<0||p.stats.happiness<30||p.stats.stability<30;return A.weightPick(outcomes.map(o=>{let q=A.outcomeScore(o),w=o.weight||1;if(q>2)w*=Math.max(.35,1+luck*.55+tm.success+sm.success+(low?tm.comeback:0));if(q<-2)w*=Math.max(.25,1-luck*.35-tm.badGuard);if(Math.abs(q)>14)w*=1+sm.extreme;return{...o,_w:w}}))};
  A.dynamicOutcome=a=>{let base={effects:{...(a.effects||{})},special:{...(a.special||{})},addTags:[...(a.addTags||[])],text:a.desc,_replace:true};if(a.fixed)return base;let r=Math.random(),p=A.p,tm=A.traitMods(),sm=A.synergyMods(),goodChance=Math.max(.12,Math.min(.48,.26+(p.stats.luck-50)*.0025+tm.success*.12+sm.success*.1));if(r<goodChance)return{...base,text:`${a.desc}。事情比预期顺利。`,effects:Object.fromEntries(Object.entries(base.effects).map(([k,v])=>[k,v>0?Math.round(v*1.45):Math.round(v*.6)])),special:{...base.special,wealth:(base.special.wealth||0)+L.rand(4000,28000)},good:true};if(r>0.72)return{...base,text:`${a.desc}。这次选择出现了反噬。`,effects:Object.fromEntries(Object.entries(base.effects).map(([k,v])=>[k,v>0?Math.round(v*.35):Math.round(v*1.35)]).concat([['happiness',-L.rand(2,7)]])),special:{...base.special,wealth:(base.special.wealth||0)-L.rand(6000,45000)}};return base};
  A.delta=(before,bw)=>{let p=A.p,a=[];for(const[k,v]of Object.entries(p.stats)){let d=v-before[k];if(d)a.push(`${L.ATTR[k]?.name||k}${d>0?'+':''}${d}`)}let dw=p.wealth-bw;if(dw)a.push(`财富${dw>0?'+':''}${L.fmtMoney(dw)}`);return a.join(' · ')||'无明显变化'};
  A.toneFrom=(before,bw)=>{let p=A.p,s=0;for(const[k,v]of Object.entries(p.stats))s+=(v-before[k]);s+=(p.wealth-bw)/18000;return s>3?'good':s<-3?'bad':'neutral'};
  A.applyOutcome=(a,z)=>{let p=A.p;if(!z._replace){Object.entries(a.effects||{}).forEach(([k,v])=>{if(k in p.stats)p.stats[k]+=v});(a.addTags||[]).forEach(t=>{if(t&&!p.tags.includes(t))p.tags.push(t)});A.special(a.special)}Object.entries(z.effects||{}).forEach(([k,v])=>{if(k in p.stats)p.stats[k]+=v});(z.addTags||[]).forEach(t=>{if(t&&!p.tags.includes(t))p.tags.push(t)});A.special(z.special);if(a.special?.grantZhou){let candidates=a.special.grantZhou.map(A.traitByName).filter(Boolean),t=L.pick(candidates);if(t){A.acquireTrait(t);z._granted=t}}if(a.special?.graduated){if(!p.tags.includes('已毕业'))p.tags.push('已毕业');p.tags=p.tags.filter(x=>x!=='大学在读')}A.clampStats(p)};

  A.autoIncome=()=>{let p=A.p,j=A.job(p.career);if(!j.salary)return;let sm=A.synergyMods(),tm=A.traitMods(),saveRate=Math.max(.1,Math.min(.55,.20+p.stats.stability*.002+p.stats.discipline*.0015-p.stats.happiness*.0005));let annual=Math.round(j.salary*12*p.salaryMul*saveRate*(p.world.careerMul||1)*(1+sm.income+tm.income));p.wealth+=annual};
  A.spouseStory=()=>{let p=A.p;if(!p.spouse||Math.random()>.22)return;let tm=A.traitMods(),sm=A.synergyMods(),arr=L.SPOUSE_STORIES||[];if(!arr.length)return;let spouse=p.spouse,story=A.weightPick(arr.map(s=>{let score=Object.values(s.effects||{}).reduce((a,b)=>a+b,0)+(s.fraction<0?-12:0);let w=s.weight||1;if(score>0)w*=1+tm.spouse+sm.spouse+(p.stats.luck-50)*.004;if(score<0)w*=Math.max(.3,1-(tm.spouse+sm.spouse)*.5);return{...s,_w:w}}));let b={...p.stats},bw=p.wealth;Object.entries(story.effects||{}).forEach(([k,v])=>p.stats[k]=L.clamp(p.stats[k]+v));if(story.wealth){let [a,z]=story.wealth;p.wealth+=L.rand(Math.min(a,z),Math.max(a,z))}if(story.fraction)p.wealth+=Math.round(Math.max(0,p.wealth)*story.fraction);if(story.tag&&!p.tags.includes(story.tag))p.tags.push(story.tag);if(story.divorce){p.spouse=null;p.tags=p.tags.filter(x=>x!=='已婚');if(!p.tags.includes('已离婚'))p.tags.push('已离婚')}A.record({age:p.age,title:'💍 伴侣',text:story.text(spouse),changes:A.delta(b,bw),tone:A.toneFrom(b,bw),kind:'spouse'})};
  A.childStory=()=>{let p=A.p;if(!p.children.length||Math.random()>.11)return;let c=L.pick(p.children),age=p.age-c.birthAge;if(age<5)return;let arr=(L.CHILD_STORIES||[]).filter(x=>!x.minParentAge||p.age>=x.minParentAge);if(!arr.length)return;let story=A.weightPick(arr),b={...p.stats},bw=p.wealth;Object.entries(story.effects||{}).forEach(([k,v])=>p.stats[k]=L.clamp(p.stats[k]+v));if(story.wealth){let[a,z]=story.wealth;p.wealth+=L.rand(Math.min(a,z),Math.max(a,z))}if(story.fraction)p.wealth+=Math.round(Math.max(0,p.wealth)*story.fraction);A.record({age:p.age,title:`👶 ${c.name}`,text:story.text(c),changes:A.delta(b,bw),tone:A.toneFrom(b,bw),kind:'child'})};
  A.maybeBirth=()=>{let p=A.p;if(!p.spouse||!p.tags.includes('已婚')||!p.tags.includes('想要孩子')||p.tags.includes('丁克')||p.children.length>=2||p.age<28||p.age>43)return;if(Math.random()<.14){let c=A.child();A.record({age:p.age,title:'👶 家庭新增成员',text:`${c.name} 出生了。`,changes:'家庭+5 · 幸福+4',tone:'good',kind:'child'});p.stats.family=L.clamp(p.stats.family+5);p.stats.happiness=L.clamp(p.stats.happiness+4)}};
  A.luckEvent=()=>{let p=A.p,sm=A.synergyMods(),chance=.025+p.stats.luck*.0007+sm.rare;if(Math.random()>Math.min(.28,chance))return;let e=L.pick(L.LUCK_EVENTS),b={...p.stats},bw=p.wealth;Object.entries(e[1]).forEach(([k,v])=>p.stats[k]=L.clamp(p.stats[k]+v));p.wealth+=e[2];p.rareEvents++;A.record({age:p.age,title:'🍀 幸运事件',text:e[0],changes:A.delta(b,bw),tone:'good',kind:'lucky'})};
  A.passiveYear=()=>{let p=A.p;if(p.tags.includes('健身习惯'))p.stats.health=L.clamp(p.stats.health+1);if(p.age>=45)p.stats.health=L.clamp(p.stats.health-L.rand(0,2));if(p.age>=65)p.stats.health=L.clamp(p.stats.health-L.rand(0,2));if(p.stats.happiness<25)p.stats.stability=L.clamp(p.stats.stability-L.rand(0,2));};
  A.record=h=>{A.p.history.unshift(h);if(h.tone==='good')A.p.positive++;else if(h.tone==='bad')A.p.negative++;else A.p.neutral++};

  A.score=()=>{let p=A.p,rar=(p.traits||[]).reduce((s,r)=>s+(L.RARITY[r.rarity]?.rank||1)*18,0),sets=Object.keys(L.SYNERGY_SETS).reduce((s,k)=>s+A.setTier(k)*22,0);return Math.round(p.age*3+Math.log10(Math.max(1,p.wealthPeak)+10)*92+p.stats.happiness*1.1+p.stats.family*.8+p.stats.intelligence*.55+p.stats.social*.35+rar+sets+p.rareEvents*22+p.careerTierPeak*30)};
  A.deathCheck=()=>{let p=A.p;if(p.stats.health<=0){A.die('健康崩溃');return true}let age=p.age,base=age<10?.00025:age<18?.00045:age<26?.0007:age<40?.0011:age<50?.0017:age<60?.003:age<70?.009:age<80?.028:age<90?.075:.19;let healthMul=1+Math.max(0,60-p.stats.health)*.018, riskMul=1+Math.max(0,p.stats.risk-55)*.012,tm=A.traitMods(),sm=A.synergyMods();let chance=base*healthMul*riskMul*tm.death*sm.death;if(age>=100)chance=.9;if(Math.random()<chance){let causes=age<18?['意外事故','突发疾病']:age<40?['交通意外','急性疾病','意外事故','运动意外']:age<65?['突发疾病','交通意外','工作相关意外','急症']:['自然衰老','突发疾病','心脑血管急症','意外跌倒'];A.die(L.pick(causes));return true}return false};
  A.die=reason=>{let p=A.p;p.alive=false;p.deathReason=reason;p.score=A.score();if(p.age===27&&p.score>=650&&!p.tags.includes('27俱乐部'))p.tags.push('27俱乐部');if(p.age<=35&&p.stats.intelligence>=90&&p.score>=850&&!p.tags.includes('天才早逝'))p.tags.push('天才早逝');p.wealthPeak=Math.max(p.wealthPeak,p.wealth);A.finishRun();localStorage.removeItem(L.STORAGE_KEY);A.syncDynasty();A.render?.()};
  A.finishRun=()=>{let p=A.p,c=A.collection();c.runs=(c.runs||0)+1;c.bestScore=Math.max(c.bestScore||0,p.score);c.bestWealth=Math.max(c.bestWealth||0,p.wealthPeak);let endings=L.ENDING_DEFS.filter(x=>x[3](p));p.endings=endings.map(x=>({id:x[0],name:x[1],rarity:x[2],desc:x[4]}));endings.forEach(x=>{if(!c.endings.includes(x[0]))c.endings.push(x[0])});A.saveCollection(c)};

  A.resolve=a=>{if(A.busy||!A.p?.alive||!A.pass(a.requires||{}))return;A.busy=true;let p=A.p,b={...p.stats},bw=p.wealth,z=a.outcomes?.length?A.pickOutcome(a.outcomes):A.dynamicOutcome(a);A.applyOutcome(a,z);p.seen[a.sourceEvent||a.id]=p.age;p.wealthPeak=Math.max(p.wealthPeak,p.wealth);p.minWealth=Math.min(p.minWealth,p.wealth);let changes=A.delta(b,bw),tone=A.toneFrom(b,bw),extra=z._granted?` · 获得强力词条【${z._granted.name}】`:'';A.record({age:p.age,title:a.title,text:(z.text||a.desc)+extra,changes,tone,kind:a.rare||a.hidden?'rare':'choice'});if(a.rare||a.hidden)p.rareEvents++;A.lastResult={text:(z.text||a.desc)+extra,changes,tone};A.autoIncome();A.spouseStory();A.childStory();A.maybeBirth();A.luckEvent();A.passiveYear();p.wealthPeak=Math.max(p.wealthPeak,p.wealth);p.minWealth=Math.min(p.minWealth,p.wealth);p.score=A.score();A.syncDynasty();if(!A.deathCheck()){p.age++;A.save();A.busy=false;A.buildYear()}else A.busy=false};
  A.save=()=>{if(A.p?.alive)localStorage.setItem(L.STORAGE_KEY,JSON.stringify(A.p))};
  A.load=()=>{try{let p=JSON.parse(localStorage.getItem(L.STORAGE_KEY));if(p?.alive){A.p=p;A.p.traits=A.p.traits||[];A.p.minWealth=A.p.minWealth??A.p.wealth;A.p.positive=A.p.positive||0;A.p.negative=A.p.negative||0;A.p.neutral=A.p.neutral||0;A.p.rareEvents=A.p.rareEvents||0;A.buildYear();A.note('已读取存档');return}}catch{}A.note('没有可读取的存档','bad')};
})();