import type {ActionChoice,ActionResponse,BaseContent,EffectOp,GameState,HistoryEntry,LegacyEvent,MetaProgress,Outcome,StatKey,TraitRef} from './types.js';
import {MemoryPersistence,Persistence,RNG,Store} from './core.js';
import {ContentProvider,eventToChoice,inferEventTheme,passes,requirement} from './content.js';
import {aggregateBuildMods,computeHiddenRoutes,computeSynergies,endingFor,findTraitEvolutions,HIDDEN_ROUTES,missedRouteHints,routeDef} from './builds.js';
import {MoneySystem,CareerSystem,RelationshipSystem,WorldSystem,FateSystem,MortalitySystem,applyOutcomeOps} from './systems/index.js';

const statKeys:StatKey[]=['health','happiness','intelligence','social','luck','ambition','stability','discipline','risk','family'];
const clamp=(a:number,b:number,v:number)=>Math.max(a,Math.min(b,v));
const avatars=['🧑‍🚀','🧑‍🎨','🧑‍💻','🧙','🥷','🧑‍🔬','🧑‍🍳','🧑‍✈️','🧑‍🚒','🧑‍⚕️','🧑‍🏫','🧑‍⚖️','🕵️','🧑‍🌾','🧑‍🎤','🧑‍🎬','🧑‍🔧','🧑‍💼','🧑‍🚀','🧑‍🎮','🧑‍🏭','🧑‍🎓','🧑‍🚓','🧑‍🚚','🧑‍🎭','🧑‍🎧','🧑‍🏋️','🧑‍🔬','🧑‍🚢','🧑‍💡'];
const defaultMeta=():MetaProgress=>({version:1,runs:0,discoveredTraits:[],discoveredSynergies:[],discoveredRoutes:[],endings:[],echoes:[]});
const uniq=<T>(a:T[])=>[...new Set(a)];

export const scoreState=(s:GameState)=>Math.round(Object.values(s.stats).reduce((a,b)=>a+b,0)*1.15+Math.log10(Math.max(1,s.wealth+200000))*120+s.careerPeak*90+s.rareEvents*35+s.relationships.filter(x=>x.affinity>55).length*20+s.synergies.reduce((n,x)=>n+x.tier*25,0));

export class GameRuntime{
  store!:Store;rng!:RNG;base!:BaseContent;money!:MoneySystem;career!:CareerSystem;relationships!:RelationshipSystem;world!:WorldSystem;fate!:FateSystem;mortality!:MortalitySystem;meta:MetaProgress=defaultMeta();
  constructor(public content:ContentProvider,public persist:Persistence=new MemoryPersistence()){}
  async init(seed=Math.floor(Math.random()*2**31),load=false){
    this.base=await this.content.base();this.meta=(await this.persist.loadMeta?.())??defaultMeta();
    if(load){const saved=await this.persist.load();if(saved){this.attach(this.normalizeState(saved));this.refreshBuildState(false);if(!this.store.get().alive)await this.finalizeRun();else await this.ensureChoices();await this.persistMeta();return this;}}
    this.newLife(seed);await this.ensureChoices();await this.persist.save(this.store.snapshot());await this.persistMeta();return this;
  }
  private normalizeState(raw:GameState){const s=structuredClone(raw) as GameState;
    s.familyResources=Number.isFinite((s as any).familyResources)?Number((s as any).familyResources):55;
    s.synergies=Array.isArray((s as any).synergies)?(s as any).synergies:[];s.routesUnlocked=Array.isArray((s as any).routesUnlocked)?(s as any).routesUnlocked:[];s.runFlags=(s as any).runFlags??{};
    s.runFlags.themeSeen=(s.runFlags.themeSeen&&typeof s.runFlags.themeSeen==='object')?s.runFlags.themeSeen:{};s.runFlags.recentCategories=Array.isArray(s.runFlags.recentCategories)?s.runFlags.recentCategories:[];
    s.ui={view:s.alive===false?'end':s.ui?.view==='info'?'info':s.ui?.view==='collection'?'collection':'game',busy:false,message:'',fast:!!(s.ui as any)?.fast};
    s.currentChoices=Array.isArray(s.currentChoices)?s.currentChoices:[];s.traits=(s.traits??[]).map(t=>this.hydrateTrait(t));
    if(s.age===1&&s.history.length===0&&s.financeHistory.length===0)s.wealth=0;
    s.wealthPeak=Math.max(s.wealthPeak??s.wealth,s.wealth);return s;
  }
  private attach(state:GameState){this.rng=new RNG(state.seed+state.age*7919+state.fate.worldline*104729);this.store=new Store(state);this.money=new MoneySystem(this.store,this.base,this.rng);this.career=new CareerSystem(this.store,this.base,this.rng);this.relationships=new RelationshipSystem(this.store,this.base,this.rng);this.world=new WorldSystem(this.store,this.rng);this.fate=new FateSystem(this.store,this.persist,this.rng);this.mortality=new MortalitySystem(this.store,this.rng);}
  private traitDef(id:string){return(this.base.TRAITS||[]).find((x:any)=>x.id===id);}
  private hydrateTrait(t:TraitRef):TraitRef{const d=this.traitDef(t.id);return d?{id:d.id,name:d.name,rarity:d.rarity,desc:d.desc,effects:{...(d.effects??{})},sets:[...(d.sets??[])],mods:{...(d.mods??{})},level:t.level??1,evolvedName:t.evolvedName,evolutionText:t.evolutionText}:{...t,level:t.level??1};}
  private rollTraits(rng:RNG,n=5):TraitRef[]{const pool=[...(this.base.TRAITS||[])],out:TraitRef[]=[];while(out.length<n&&pool.length){const t=rng.weighted(pool,x=>Math.max(.1,Number(this.base.RARITY?.[x.rarity]?.weight??1)));out.push(this.hydrateTrait({id:t.id,name:t.name,rarity:t.rarity}));pool.splice(pool.indexOf(t),1);}return out;}
  private applyStartingTraitEffects(stats:GameState['stats'],traits:TraitRef[]){for(const t of traits)for(const[k,v]of Object.entries(t.effects??{}))if(k in stats&&Number.isFinite(v))stats[k as StatKey]=clamp(0,200,stats[k as StatKey]+Number(v));}
  private newLife(seed:number){const rng=new RNG(seed),b=rng.pick(this.base.BACKGROUNDS),world=rng.pick(this.base.WORLDS),pe=rng.pick(this.base.PERSONALITIES),ta=rng.pick(this.base.TALENTS),fl=rng.pick(this.base.FLAWS);const stats={} as GameState['stats'];for(const k of statKeys)stats[k]=rng.int(38,72);stats.family=Number(b?.[2]??55);for(const src of[pe?.[1]??{},ta?.[1]??{},fl?.[1]??{}])for(const[k,v]of Object.entries(src))if(k in stats)stats[k as StatKey]=clamp(0,200,stats[k as StatKey]+Number(v));const traits=this.rollTraits(rng);this.applyStartingTraitEffects(stats,traits);
    const echo=this.meta.echoes.length&&rng.next()<.34?rng.pick(this.meta.echoes.slice(-6)):undefined;const tags=[String(b?.[3]??''),String(pe?.[0]??''),String(ta?.[0]??''),String(fl?.[0]??'')].filter(Boolean);if(echo)tags.push(`前世回响:${echo}`);
    const state:GameState={version:'V7',id:`life_${seed}_${Date.now()}`,seed,name:'你',gender:rng.pick(['男','女']),avatar:rng.int(0,avatars.length-1),age:1,alive:true,deathReason:'',background:String(b?.[0]??'普通家庭'),worldName:String(world?.name??'普通时代'),familyResources:clamp(0,100,Number(b?.[1]??50)),stats,traits,synergies:[],routesUnlocked:[],tags,wealth:0,wealthPeak:0,careerRoute:null,careerLevel:0,careerYears:0,careerPeak:0,education:'未定',relationships:[],socialLinks:[],partnerId:null,children:[],world:{economy:rng.int(38,68),jobs:rng.int(38,68),tech:rng.int(35,70),market:rng.int(35,70),medicine:rng.int(38,68),conflict:rng.int(28,65),housing:rng.int(38,70),headline:'世界刚刚开始运行。'},history:[],yearStories:[],ledger:null,financeHistory:[],seen:{},fate:{targetAge:rng.int(19,30),triggered:false,worldline:1},positive:0,negative:0,neutral:0,rareEvents:0,score:0,runFlags:{echo,themeSeen:{},recentCategories:[]},currentChoices:[],ui:{view:'game',busy:false,message:'',fast:false}};this.attach(state);this.refreshBuildState(false);this.noteTraits();}
  avatarEmoji(index:number){return avatars[index%avatars.length]!;}
  async reroll(seed=Math.floor(Math.random()*2**31)){this.newLife(seed);await this.ensureChoices();await this.persist.save(this.store.snapshot());await this.persistMeta();}

  private noteTraits(){this.meta.discoveredTraits=uniq([...this.meta.discoveredTraits,...this.store.get().traits.map(t=>t.id)]);}
  private refreshBuildState(recordEvolution=true){let s=this.store.get();const synergies=computeSynergies(s);this.store.dispatch({type:'SYNERGIES',value:synergies});s=this.store.get();const routes=uniq([...s.routesUnlocked,...computeHiddenRoutes(s)]);this.store.dispatch({type:'ROUTES',value:routes});s=this.store.get();
    if(recordEvolution){for(const e of findTraitEvolutions(s)){this.store.dispatch({type:'TRAIT_EVOLVE',id:e.id,name:e.name,text:e.text});this.store.dispatch({type:'HISTORY',entry:{age:s.age,title:`✦ 命格进化 · ${e.name}`,text:e.text,tone:'good',kind:'evolution',sourceId:`evolve:${e.id}`,rarity:'prismatic'}});}}
    this.meta.discoveredSynergies=uniq([...this.meta.discoveredSynergies,...this.store.get().synergies.map(x=>x.id)]);this.meta.discoveredRoutes=uniq([...this.meta.discoveredRoutes,...this.store.get().routesUnlocked]);this.noteTraits();
  }
  private async persistMeta(){await this.persist.saveMeta?.(this.meta);}
  metaSnapshot(){return structuredClone(this.meta);}

  private zhouTheme(name:string){if(/书|笔|卷|拼图|积木/.test(name))return{tag:'抓周·书卷气',trait:'curious'};if(/钱|币|算盘/.test(name))return{tag:'抓周·钱串子',trait:'cashflow_eye'};if(/工具|锤|螺/.test(name))return{tag:'抓周·工具控',trait:'engineering_brain'};if(/麦|舞|琴|鼓|相机|画笔/.test(name))return{tag:'抓周·舞台感',trait:'camera_face'};if(/球|运动|铲/.test(name))return{tag:'抓周·运动魂',trait:'sports_gift'};return{tag:`抓周·${name}`,trait:'curious'};}
  private scaleOps(eff:Record<string,unknown>,scale:number):EffectOp[]{return Object.entries(eff).filter(([k,v])=>statKeys.includes(k as StatKey)&&Number.isFinite(v)).map(([k,v])=>({type:'stat',key:k as StatKey,delta:Math.round(Number(v)*scale)}));}
  private zhouChoices():ActionChoice[]{const raw=this.rng.shuffle(this.base.ZHOU_CHOICES||[]).slice(0,5);return raw.map((z:any,i)=>{const name=String(z?.[0]??`物件${i+1}`),emoji=String(z?.[1]??'🎲'),eff=z?.[3]??{},theme=this.zhouTheme(name);return{id:`zhou:${name}`,sourceEvent:'zhou',category:'抓周',title:`${emoji} ${name}`,desc:'你伸手去抓它。真正的结果要在抓到以后才揭晓。',hint:'三个结果档位：普通 / 出彩 / 天胡。选择前不会提前染色。',outcomes:[
      {weight:68,text:`你抓住了${name}，玩了一会儿就被别的东西吸引。大人们笑着拍了拍手。`,tone:'neutral',rarity:'normal',ops:this.scaleOps(eff,.35)},
      {weight:26,text:`你对${name}表现出明显兴趣，怎么拿都不肯放。有人说这孩子以后也许真会沿着这个方向走。`,tone:'good',rarity:'notable',ops:[...this.scaleOps(eff,.78),{type:'tag',tag:theme.tag}]},
      {weight:6,text:`你抓到${name}以后出现了异常鲜明的反应。屋里安静了一秒，所有大人都记住了这一幕。`,tone:'good',rarity:'prismatic',ops:[...this.scaleOps(eff,1.35),{type:'tag',tag:theme.tag},{type:'traitAdd',id:theme.trait}]}
    ]};});}
  private educationChoices():ActionChoice[]{const defs=[['数理工科','把时间押在数理、工程与技术上','intelligence'],['医学路线','进入漫长而严格的医学训练','discipline'],['艺术传媒','把表达与审美当成职业筹码','happiness'],['商科人文','把组织、商业、法律与表达当成工具','social'],['警校路线','选择秩序、纪律与公共责任','stability']] as [string,string,StatKey][];return defs.map(([v,d,k])=>({id:`edu:${v}`,sourceEvent:'education',category:'教育',title:v,desc:d,hint:'专业会改变职业与隐藏路线池，但不会锁死转行。',outcomes:[{weight:1,text:`你选择了${v}。`,tone:'neutral',ops:[{type:'education',value:v},{type:'tag',tag:v},{type:'stat',key:k,delta:7}]}]}));}
  private careerChoices():ActionChoice[]{const s=this.store.get();let routes=[...this.base.CAREER_ROUTES];if(/数理|工程/.test(s.education))routes=routes.filter(r=>['科技','游戏','工程','科研','制造'].includes(r.group));else if(/医学/.test(s.education))routes=routes.filter(r=>['医疗','科研'].includes(r.group));else if(/艺术/.test(s.education))routes=routes.filter(r=>['创意','演艺','内容','传媒','游戏'].includes(r.group));else if(/商科|人文/.test(s.education))routes=routes.filter(r=>['金融','商业','法律','咨询','传媒','公共'].includes(r.group));else if(/警校/.test(s.education))routes=routes.filter(r=>['公共','法律','交通'].includes(r.group));if(routes.length<4)routes=[...this.base.CAREER_ROUTES];return this.rng.shuffle(routes).slice(0,4).map(r=>({id:`career:${r.id}`,sourceEvent:'career_start',category:'职业',title:`${r.icon} ${r.titles[0]}`,desc:`进入${r.group}路线，从第一阶开始。`,hint:`这条路线一共有 ${r.titles.length} 阶，可以晋升也可以转行。`,outcomes:[{weight:1,text:`你进入了${r.titles[0]}岗位。`,tone:'neutral',ops:[{type:'careerSet',route:r.id,level:1}]}]}));}
  private fallbacks():ActionChoice[]{return[
    {id:'fb:rest',sourceEvent:'fallback',category:'生活',title:'给自己留一点空白',desc:'少做一些事，看看精神状态会不会回来。',hint:'恢复，但可能错过机会',outcomes:[{weight:1,text:'这一年没有大突破，但你重新找回了一些呼吸感。',tone:'good',ops:[{type:'stat',key:'happiness',delta:6},{type:'stat',key:'health',delta:2}]}]},
    {id:'fb:skill',sourceEvent:'fallback',category:'成长',title:'学一个真正会用到的技能',desc:'不是为了证书，而是为了让自己多一条路。',hint:'长期能力积累',outcomes:[{weight:1,text:'你没有立刻变强很多，但这项技能后来多次派上用场。',tone:'good',ops:[{type:'stat',key:'intelligence',delta:5},{type:'stat',key:'discipline',delta:3}]}]},
    {id:'fb:health',sourceEvent:'fallback',category:'健康',title:'认真处理一个拖了很久的身体问题',desc:'不再靠“应该没事”来处理健康。',hint:'降低长期风险',outcomes:[{weight:1,text:'问题没有奇迹般消失，但你至少开始认真处理它。',tone:'good',ops:[{type:'stat',key:'health',delta:6}]}]},
    {id:'fb:family',sourceEvent:'fallback',category:'家庭',title:'把时间留给真正重要的人',desc:'没有 KPI，只是别让关系永远排在最后。',hint:'家庭关系与幸福倾向',outcomes:[{weight:1,text:'这一年你没有因此变得更成功，但有些关系没有继续变淡。',tone:'good',ops:[{type:'stat',key:'family',delta:5},{type:'stat',key:'happiness',delta:2}]}]}
  ];}
  private echoChoice():ActionChoice|null{const s=this.store.get(),echo=s.runFlags.echo;if(!echo||s.age<10||s.age>18||s.seen.echo_memory!=null)return null;return{id:'echo:memory',sourceEvent:'echo_memory',category:'前世回响',title:'一个你从未经历过的场景突然很熟悉',desc:`你说不清为什么，但「${echo}」这几个字像从很远的地方传回来。`,hint:'跨周目记忆只给一个微小偏置，不直接送你一局胜利。',rare:true,outcomes:[{weight:1,text:'那种熟悉感很快消失，但你在一个关键选择上比别人早想了一步。',tone:'good',rarity:'notable',ops:[{type:'stat',key:'luck',delta:4},{type:'stat',key:'intelligence',delta:3}]}]};}
  private eligibleLegacy(e:LegacyEvent){const s=this.store.get();if(s.age<e.minAge||s.age>e.maxAge||!passes(s,requirement(e.requires)))return false;const seen=s.seen[e.id];if(seen!=null){if(!e.repeatable)return false;if(s.age-seen<(e.cooldown??4))return false;}const theme=inferEventTheme(e),themeAge=s.runFlags.themeSeen?.[theme];if(themeAge!=null&&s.age-themeAge<=2&&!e.hidden)return false;if(e.category==='投资'&&!s.tags.includes('投资者'))return false;if(e.hidden){const mods=aggregateBuildMods(s),p=.07+Math.max(0,s.stats.luck-50)*.0015+Math.max(0,mods.rare??0)*.35;if(this.rng.next()>clamp(.04,.48,p))return false;}return true;}
  private eventWeight(e:LegacyEvent,picked:ActionChoice[]){const s=this.store.get(),theme=inferEventTheme(e),sameTheme=picked.some(c=>String(c.meta?.theme??'')===theme),sameCategory=picked.filter(c=>c.category===e.category).length,last=s.runFlags.themeSeen?.[theme],recent=s.runFlags.recentCategories??[];let w=Math.max(.05,Number(e.weight??1));if(sameTheme)w*=.05;if(sameCategory===1)w*=.42;if(sameCategory>=2)w*=.06;if(last!=null){const d=s.age-last;if(d<=4)w*=.22;else if(d<=7)w*=.55;}if(recent.slice(-3).includes(e.category))w*=.72;return w;}
  private addDiverseEvents(events:LegacyEvent[],picked:ActionChoice[],limit=4){let pool=events.map(e=>({e,c:eventToChoice(e,this.store.get(),this.rng)})).filter((x):x is {e:LegacyEvent,c:ActionChoice}=>!!x.c);while(pool.length&&picked.length<limit){const chosen=this.rng.weighted(pool,x=>this.eventWeight(x.e,picked));picked.push(chosen.c);pool=pool.filter(x=>x!==chosen);}return picked;}
  private rememberChoiceTheme(choice:ActionChoice){const s=this.store.get(),theme=String(choice.meta?.theme??''),cats=[...(s.runFlags.recentCategories??[]),choice.category].slice(-6),themeSeen={...(s.runFlags.themeSeen??{})};if(theme)themeSeen[theme]=s.age;this.store.dispatch({type:'RUN_FLAGS',patch:{themeSeen,recentCategories:cats}});}

  private routeArcChoice(id:string):ActionChoice|null{const s=this.store.get(),d=routeDef(id);if(!d)return null;const first=`route:${id}:1`,second=`route:${id}:2`,a=s.seen[first],b=s.seen[second];
    if(a==null){const map:Record<string,ActionChoice>={
      solo_company:{id:first,sourceEvent:first,category:'隐藏路线',title:'把副业压缩成「一个人公司」',desc:'技术、产品、销售、自动化都由你自己组织。',hint:d.desc,rare:true,outcomes:[{weight:6,text:'你做出了第一个真正有人愿意付钱的产品。规模不大，但闭环成立了。',tone:'good',rarity:'prismatic',ops:[{type:'tag',tag:'一个人公司'},{type:'tag',tag:'副业跑通'},{type:'stat',key:'discipline',delta:6},{type:'stat',key:'ambition',delta:5}]},{weight:3,text:'产品没有立刻跑起来，但你第一次完整走完了从需求到交付的流程。',tone:'neutral',ops:[{type:'tag',tag:'一个人公司'},{type:'stat',key:'intelligence',delta:4}]}]},
      capital_architect:{id:first,sourceEvent:first,category:'隐藏路线',title:'写下自己的「投资宪法」',desc:'仓位、风险、止损、长期收益目标全部提前写死。',hint:d.desc,rare:true,outcomes:[{weight:1,text:'你第一次把“不要犯大错”放在了“赚最多”前面。',tone:'good',rarity:'notable',ops:[{type:'tag',tag:'风险纪律'},{type:'stat',key:'stability',delta:7},{type:'stat',key:'discipline',delta:5}]}]},
      signature_creator:{id:first,sourceEvent:first,category:'隐藏路线',title:'开始做一件不迎合算法的代表作',desc:'它未必赚钱，但你想知道自己的上限到底在哪里。',hint:d.desc,rare:true,outcomes:[{weight:5,text:'作品没有立刻爆，但第一次有人因为“这是你的东西”而记住它。',tone:'good',rarity:'notable',ops:[{type:'tag',tag:'内容创作者'},{type:'stat',key:'happiness',delta:7},{type:'stat',key:'discipline',delta:4}]},{weight:2,text:'它几乎无人问津。你第一次认真怀疑“个人风格”是不是自我感动。',tone:'bad',ops:[{type:'tag',tag:'内容创作者'},{type:'stat',key:'happiness',delta:-5},{type:'stat',key:'stability',delta:3}]}]},
      family_dynasty:{id:first,sourceEvent:first,category:'隐藏路线',title:'把家庭财务和长期责任真正摊开来谈',desc:'钱、孩子、父母、职业选择不再各自独立。',hint:d.desc,rare:true,outcomes:[{weight:1,text:'你们第一次像一个长期共同体一样讨论未来，而不是各自处理眼前问题。',tone:'good',rarity:'notable',ops:[{type:'tag',tag:'家族支柱'},{type:'stat',key:'family',delta:8},{type:'stat',key:'stability',delta:5}]}]},
      second_curve:{id:first,sourceEvent:first,category:'隐藏路线',title:'承认第一条路已经走不通',desc:'把沉没成本留在原地，重新搭第二条增长曲线。',hint:d.desc,rare:true,outcomes:[{weight:5,text:'你没有立刻翻身，但终于停止给错误方向继续加码。',tone:'good',rarity:'notable',ops:[{type:'tag',tag:'第二曲线'},{type:'stat',key:'ambition',delta:7},{type:'stat',key:'stability',delta:6}]},{weight:2,text:'转型比想象更痛，你一度同时失去旧收入和新方向。',tone:'bad',ops:[{type:'tag',tag:'第二曲线'},{type:'stat',key:'happiness',delta:-6},{type:'stat',key:'risk',delta:4}]}]},
      century_witness:{id:first,sourceEvent:first,category:'隐藏路线',title:'开始整理自己亲历过的时代',desc:'很多年轻人只在历史里见过的东西，你记得它发生时的气味。',hint:d.desc,rare:true,outcomes:[{weight:1,text:'你开始把几十年的变化记录下来。别人第一次意识到，你本身就是一份活档案。',tone:'good',rarity:'prismatic',ops:[{type:'tag',tag:'世纪见证者'},{type:'stat',key:'happiness',delta:6}]}]}
    };return map[id]??null;}
    if(b==null&&s.age>=a+3){const map:Record<string,ActionChoice>={
      solo_company:{id:second,sourceEvent:second,category:'路线进化',title:'一个人公司撞上第一次真正的规模瓶颈',desc:'继续一个人扛，还是把流程变成系统？',hint:'这是前几年选择留下的后果。',rare:true,responses:[{label:'继续产品化和自动化',requires:{statsMin:{discipline:75}},hint:'需要自律达到长期主义水平',outcomes:[{weight:5,text:'你把重复工作一点点变成系统，收入第一次不再和工时完全绑定。',tone:'good',rarity:'prismatic',ops:[{type:'money',source:'route',label:'产品化现金流',amount:180000},{type:'stat',key:'discipline',delta:4}]},{weight:2,text:'自动化投入比预期大，短期现金流承压。',tone:'bad',ops:[{type:'money',source:'route',label:'系统重构成本',amount:-80000},{type:'stat',key:'intelligence',delta:3}]}]},{label:'招第一个真正的搭档',requires:{statsMin:{social:60}},hint:'需要一定社交能力',outcomes:[{weight:1,text:'你第一次把一部分命运交给另一个人，业务边界反而被打开了。',tone:'good',ops:[{type:'stat',key:'social',delta:6},{type:'stat',key:'ambition',delta:3}]}]}],outcomes:[]},
      capital_architect:{id:second,sourceEvent:second,category:'路线进化',title:'市场暴跌，投资宪法第一次接受实战',desc:'所有人都在说“这次不一样”。',hint:'风险纪律会真正参与结果权重。',rare:true,outcomes:[{weight:5,text:'你没有抄到最低点，但仓位活了下来。几个月后你发现这比预测正确更重要。',tone:'good',rarity:'prismatic',ops:[{type:'money',source:'route',label:'周期后的资产收益',amount:120000},{type:'stat',key:'stability',delta:5}]},{weight:2,text:'你还是在恐慌里打破了自己的规则。损失不致命，但很难受。',tone:'bad',ops:[{type:'money',source:'route',label:'纪律失守损失',amount:-90000},{type:'stat',key:'happiness',delta:-4}]}]},
      signature_creator:{id:second,sourceEvent:second,category:'路线进化',title:'有人愿意为你的风格下注',desc:'商业化会放大作品，也可能稀释它。',hint:'代表作路线进入第二阶段。',rare:true,responses:[{label:'接受资源，但守住最终决定权',outcomes:[{weight:4,text:'资源放大了你的作品，而没有完全吃掉它。你第一次拥有真正意义上的代表作。',tone:'good',rarity:'prismatic',ops:[{type:'money',source:'route',label:'代表作收入',amount:150000},{type:'stat',key:'social',delta:5},{type:'stat',key:'happiness',delta:8}]},{weight:2,text:'合作并不顺利，但你更清楚下一次什么不能让。',tone:'neutral',ops:[{type:'stat',key:'stability',delta:4}]}]},{label:'拒绝商业化，继续自己做',outcomes:[{weight:1,text:'它仍然小众，但几乎完整地属于你。',tone:'good',ops:[{type:'stat',key:'happiness',delta:10},{type:'stat',key:'ambition',delta:-2}]}]}],outcomes:[]},
      second_curve:{id:second,sourceEvent:second,category:'路线进化',title:'第二条曲线终于出现第一个陡坡',desc:'过去的失败经验突然开始变成优势。',hint:'不是回到原点，而是带着旧经验重新开始。',rare:true,outcomes:[{weight:5,text:'你终于重新进入增长区间。最重要的是，这次你知道自己为什么能起来。',tone:'good',rarity:'prismatic',ops:[{type:'money',source:'route',label:'第二曲线收入',amount:140000},{type:'stat',key:'stability',delta:5},{type:'stat',key:'ambition',delta:5}]},{weight:2,text:'它还没有真正起飞，但至少没有再次掉回旧坑。',tone:'neutral',ops:[{type:'stat',key:'discipline',delta:4}]}]}
    };return map[id]??null;}
    return null;
  }
  private routeChoice():ActionChoice|null{const s=this.store.get(),candidates=s.routesUnlocked.map(id=>this.routeArcChoice(id)).filter((x):x is ActionChoice=>!!x);return candidates.length?this.rng.pick(candidates):null;}

  async draftChoices():Promise<ActionChoice[]>{const s=this.store.get();if(!s.alive)return[];if(s.age===1)return this.zhouChoices();if(this.fate.isDue()){if(!s.fate.snapshotKey)await this.fate.capture();return this.fate.choices();}if(s.age===18)return this.educationChoices();if(s.age===22&&!s.careerRoute)return this.careerChoices();
    const picked:ActionChoice[]=[];const echo=this.echoChoice();if(echo)picked.push(echo);const route=this.routeChoice();if(route&&this.rng.next()<.62)picked.push(route);const major=this.relationships.majorChoice();if(major&&picked.length<3)picked.push(major);const events=(await this.content.events(s.age)).filter(e=>this.eligibleLegacy(e));this.addDiverseEvents(events,picked,4);for(const f of this.rng.shuffle(this.fallbacks())){if(picked.length>=4)break;if(!picked.some(x=>x.category===f.category))picked.push(f);}for(const f of this.rng.shuffle(this.fallbacks())){if(picked.length>=4)break;picked.push(f);}let choices=picked.slice(0,4);const promo=this.career.promotionChoice();if(promo&&this.rng.next()<.35){const replaceable=choices.map((c,i)=>({c,i})).filter(x=>x.c.sourceEvent==='fallback'||choices.filter(y=>y.category===x.c.category).length>1);const slot=replaceable.length?this.rng.pick(replaceable).i:this.rng.int(0,choices.length-1);choices[slot]=promo;}return choices;}
  async ensureChoices(){if(this.store.get().alive&&this.store.get().currentChoices.length===0)this.store.dispatch({type:'SET_CHOICES',choices:await this.draftChoices()});}
  private pickOutcome(c:ActionChoice,pool:Outcome[]):Outcome{const s=this.store.get(),mods=aggregateBuildMods(s);return this.rng.weighted(pool,o=>{let w=Math.max(.01,o.weight);if(o.tone==='good')w*=1+(s.stats.luck-50)*.004+(s.stats.discipline-50)*.0015+Math.max(-.2,mods.success??0);if(o.tone==='bad')w*=Math.max(.28,1-(s.stats.luck-50)*.002-Math.max(0,mods.badGuard??0));if(o.rarity==='prismatic')w*=1+Math.max(0,mods.rare??0);if((mods.comeback??0)>0&&(s.wealth<0||s.negative>s.positive+3)&&o.tone==='good')w*=1+(mods.comeback??0);return Math.max(.03,w)});}
  private applyBuildOps(ops:EffectOp[]){for(const op of ops){if(op.type==='traitAdd'){if(this.store.get().traits.some(t=>t.id===op.id))continue;const d=this.traitDef(op.id);if(!d)continue;const t=this.hydrateTrait({id:d.id,name:d.name,rarity:d.rarity});this.store.dispatch({type:'TRAIT_ADD',trait:t});for(const[k,v]of Object.entries(t.effects??{}))if(statKeys.includes(k as StatKey)&&Number.isFinite(v))this.store.dispatch({type:'STAT',key:k as StatKey,delta:Number(v)});}else if(op.type==='traitEvolve')this.store.dispatch({type:'TRAIT_EVOLVE',id:op.id,name:op.name,text:op.text});}}
  private microStory():HistoryEntry|null{const s=this.store.get(),defs=this.base.MICRO_STORIES??[],recent=new Set(s.history.slice(0,24).map(h=>h.title));let candidates=defs.filter(x=>s.age>=x.min&&s.age<=x.max&&!recent.has(x.title));if(!candidates.length)candidates=defs.filter(x=>s.age>=x.min&&s.age<=x.max);if(!candidates.length)return null;const e=this.rng.pick(candidates),ops=Object.entries(e.effects??{}).filter(([k,v])=>statKeys.includes(k as StatKey)&&Number.isFinite(v)).map(([k,v])=>({type:'stat',key:k as StatKey,delta:Number(v)} as EffectOp)),pseudo:ActionChoice={id:`micro:${e.title}`,sourceEvent:`micro:${e.title}`,category:'生活切片',title:e.title,desc:e.text,outcomes:[]},out:Outcome={weight:1,text:e.text,tone:e.tone,ops};applyOutcomeOps(this.store,pseudo,out,this.relationships,this.career);return{age:s.age,title:e.title,text:e.text,tone:e.tone,kind:'incident',changes:'生活把轨迹轻轻拨动了一点',sourceId:`micro:${e.title}`};}
  private changes(before:GameState,after:GameState){const parts:string[]=[];for(const k of statKeys){const d=after.stats[k]-before.stats[k];if(Math.abs(d)>=2)parts.push(`${this.base.ATTR[k]?.name??k}${d>0?'有所提升':'有所下降'}`)}const mw=after.wealth-before.wealth;if(Math.abs(mw)>=100)parts.push(`财富${mw>0?'+':''}${Math.round(mw/1000)/10}万`);const added=after.traits.filter(t=>!before.traits.some(b=>b.id===t.id));if(added.length)parts.push(`获得命格「${added[0]!.evolvedName??added[0]!.name}」`);return parts.slice(0,4).join(' · ')||'没有明显变化';}
  private eligibleResponse(c:ActionChoice,responseIndex?:number):ActionResponse|null{const s=this.store.get();if(!c.responses?.length)return null;if(responseIndex!=null){const r=c.responses[responseIndex];return r&&passes(s,r.requires)?r:null;}return c.responses.find(r=>passes(s,r.requires))??null;}
  async resolve(index:number,responseIndex?:number){const s0=this.store.get();if(s0.ui.busy||!s0.alive)return;const choice=s0.currentChoices[index];if(!choice||!passes(s0,choice.requires))return;const response=this.eligibleResponse(choice,responseIndex);if(choice.responses?.length&&!response)return;const pool=response?.outcomes??choice.outcomes;if(!pool.length)return;const before=this.store.snapshot();this.store.dispatch({type:'UI_BUSY',value:true});try{
      this.money.begin();const out=this.pickOutcome(choice,pool);applyOutcomeOps(this.store,choice,out,this.relationships,this.career);this.applyBuildOps(out.ops);if(choice.sourceEvent==='lachesis')this.fate.commit(String(choice.meta?.fateBranch??'unknown'));const s1=this.store.get();this.store.dispatch({type:'SEEN',id:choice.sourceEvent,age:s1.age});this.rememberChoiceTheme(choice);const hist:HistoryEntry={age:s1.age,title:response?`${choice.title} · ${response.label}`:choice.title,text:out.text,tone:out.tone??'neutral',kind:choice.rare||out.rarity==='prismatic'?'rare':'choice',changes:this.changes(before,this.store.snapshot()),sourceId:choice.sourceEvent,rarity:out.rarity};this.store.dispatch({type:'HISTORY',entry:hist});if(choice.sourceEvent==='zhou')this.store.dispatch({type:'RUN_FLAGS',patch:{zhouResult:out.rarity??'normal'}});
      this.world.tick();this.career.tick();this.relationships.tick();const extraCount=this.rng.next()<.48?0:this.rng.next()<.82?1:2;for(let i=0;i<extraCount&&this.store.get().yearStories.length<3;i++){const m=this.microStory();if(m)this.store.dispatch({type:'HISTORY',entry:m});}this.money.annual();this.refreshBuildState(true);const died=this.mortality.check();const snap=this.store.snapshot();snap.score=scoreState(snap);snap.careerPeak=Math.max(snap.careerPeak,snap.careerLevel);this.store.replace(snap);
      if(!died){this.store.dispatch([{type:'ADVANCE_AGE'},{type:'SET_CHOICES',choices:[]}]);this.store.dispatch({type:'SET_CHOICES',choices:await this.draftChoices()});}else await this.finalizeRun();
      this.store.dispatch({type:'UI_BUSY',value:false});await this.persist.save(this.store.snapshot());await this.persistMeta();
    }catch(e){console.error('[V8.1] yearly transaction rollback',e);this.store.replace(before);this.store.dispatch({type:'UI_MESSAGE',value:'这一年处理异常，已完整回滚。'});}finally{if(this.store.get().ui.busy)this.store.dispatch({type:'UI_BUSY',value:false});}
  }
  private async finalizeRun(){const s=this.store.get();if(s.runFlags.metaFinalized)return;const e=endingFor(s);this.store.dispatch({type:'RUN_FLAGS',patch:{endingId:e.id,endingTitle:e.title,metaFinalized:true}});this.meta.runs++;this.meta.endings=uniq([...this.meta.endings,e.id]);const echo=s.synergies[0]?.name??routeDef(s.routesUnlocked[0]??'')?.title??e.title;this.meta.echoes=uniq([...this.meta.echoes,echo]).slice(-12);await this.persistMeta();}
  async rewindFate(){const ok=await this.fate.rewind();if(ok){const normalized=this.normalizeState(this.store.snapshot());this.attach(normalized);this.refreshBuildState(false);this.store.dispatch({type:'SET_CHOICES',choices:this.fate.choices()});await this.persist.save(this.store.snapshot());}return ok;}
  ending(){return endingFor(this.store.get());}
  missedRouteHints(){return missedRouteHints(this.store.get());}
  routeCatalog(){return HIDDEN_ROUTES;}
}
