import type {ActionChoice,BaseContent,GameState,HistoryEntry,LegacyEvent,Outcome,StatKey,Tone,TraitRef} from './types.js';
import {MemoryPersistence,Persistence,RNG,Store} from './core.js';
import {ContentProvider,eventToChoice,passes,requirement} from './content.js';
import {MoneySystem,CareerSystem,RelationshipSystem,WorldSystem,FateSystem,MortalitySystem,applyOutcomeOps} from './systems/index.js';

const statKeys:StatKey[]=['health','happiness','intelligence','social','luck','ambition','stability','discipline','risk','family'];
const clamp=(a:number,b:number,v:number)=>Math.max(a,Math.min(b,v));
const avatars=['🧑‍🚀','🧑‍🎨','🧑‍💻','🧙','🥷','🧑‍🔬','🧑‍🍳','🧑‍✈️','🧑‍🚒','🧑‍⚕️','🧑‍🏫','🧑‍⚖️','🕵️','🧑‍🌾','🧑‍🎤','🧑‍🎬','🧑‍🔧','🧑‍💼','🧑‍🚀','🧑‍🎮','🧑‍🏭','🧑‍🎓','🧑‍🚓','🧑‍🚚','🧑‍🎭','🧑‍🎧','🧑‍🏋️','🧑‍🔬','🧑‍🚢','🧑‍💡'];

export const scoreState=(s:GameState)=>Math.round(Object.values(s.stats).reduce((a,b)=>a+b,0)*1.15+Math.log10(Math.max(1,s.wealth+200000))*120+s.careerPeak*90+s.rareEvents*35+s.relationships.filter(x=>x.affinity>55).length*20);

export class GameRuntime{
  store!:Store;rng!:RNG;base!:BaseContent;money!:MoneySystem;career!:CareerSystem;relationships!:RelationshipSystem;world!:WorldSystem;fate!:FateSystem;mortality!:MortalitySystem;
  constructor(public content:ContentProvider,public persist:Persistence=new MemoryPersistence()){}
  async init(seed=Math.floor(Math.random()*2**31),load=false){this.base=await this.content.base();if(load){const saved=await this.persist.load();if(saved){this.attach(saved);await this.ensureChoices();return this;}}this.newLife(seed);await this.ensureChoices();await this.persist.save(this.store.snapshot());return this;}
  private attach(state:GameState){this.rng=new RNG(state.seed+state.age*7919+state.fate.worldline*104729);this.store=new Store(state);this.money=new MoneySystem(this.store,this.base,this.rng);this.career=new CareerSystem(this.store,this.base,this.rng);this.relationships=new RelationshipSystem(this.store,this.base,this.rng);this.world=new WorldSystem(this.store,this.rng);this.fate=new FateSystem(this.store,this.persist,this.rng);this.mortality=new MortalitySystem(this.store,this.rng);}
  private rollTraits(rng:RNG,n=5):TraitRef[]{const pool=[...(this.base.TRAITS||[])],out:TraitRef[]=[];while(out.length<n&&pool.length){const t=rng.weighted(pool,x=>Math.max(.1,Number(this.base.RARITY?.[x.rarity]?.weight??1)));out.push({id:t.id,name:t.name,rarity:t.rarity});pool.splice(pool.indexOf(t),1);}return out;}
  private newLife(seed:number){const rng=new RNG(seed),b=rng.pick(this.base.BACKGROUNDS),world=rng.pick(this.base.WORLDS),pe=rng.pick(this.base.PERSONALITIES),ta=rng.pick(this.base.TALENTS),fl=rng.pick(this.base.FLAWS);const stats={} as GameState['stats'];for(const k of statKeys)stats[k]=rng.int(38,72);stats.family=Number(b?.[2]??55);for(const src of[pe?.[1]??{},ta?.[1]??{},fl?.[1]??{}])for(const[k,v]of Object.entries(src))if(k in stats)stats[k as StatKey]=clamp(0,200,stats[k as StatKey]+Number(v));const wealth=Math.max(0,Number(b?.[1]??45)*1000+rng.int(-12000,22000));const state:GameState={version:'V7',id:`life_${seed}_${Date.now()}`,seed,name:'你',gender:rng.pick(['男','女']),avatar:rng.int(0,avatars.length-1),age:1,alive:true,deathReason:'',background:String(b?.[0]??'普通家庭'),worldName:String(world?.name??'普通时代'),stats,traits:this.rollTraits(rng),tags:[String(b?.[3]??''),String(pe?.[0]??''),String(ta?.[0]??''),String(fl?.[0]??'')].filter(Boolean),wealth,wealthPeak:wealth,careerRoute:null,careerLevel:0,careerYears:0,careerPeak:0,education:'未定',relationships:[],socialLinks:[],partnerId:null,children:[],world:{economy:rng.int(38,68),jobs:rng.int(38,68),tech:rng.int(35,70),market:rng.int(35,70),medicine:rng.int(38,68),conflict:rng.int(28,65),housing:rng.int(38,70),headline:'世界刚刚开始运行。'},history:[],yearStories:[],ledger:null,financeHistory:[],seen:{},fate:{targetAge:rng.int(19,30),triggered:false,worldline:1},positive:0,negative:0,neutral:0,rareEvents:0,score:0,currentChoices:[],ui:{view:'game',busy:false,message:''}};this.attach(state);}
  avatarEmoji(index:number){return avatars[index%avatars.length]!;}
  async reroll(seed=Math.floor(Math.random()*2**31)){this.newLife(seed);await this.ensureChoices();await this.persist.save(this.store.snapshot());}
  private zhouChoices():ActionChoice[]{const s=this.store.get(),raw=this.rng.shuffle(this.base.ZHOU_CHOICES||[]).slice(0,5);return raw.map((z:any,i)=>{const name=String(z?.[0]??`抓周${i+1}`),emoji=String(z?.[1]??'🎲'),eff=z?.[3]??{};return{id:`zhou:${name}`,sourceEvent:'zhou',category:'抓周',title:`${emoji} ${name}`,desc:'选择一个童年最早的倾向。',hint:'它不会决定你，但会在很长时间里留下偏向。',rare:true,outcomes:[{weight:1,text:`你抓住了${name}。大人们笑着替你解释未来，而你只觉得手里的东西很有意思。`,tone:'good',ops:Object.entries(eff).map(([k,v])=>({type:'stat',key:k as StatKey,delta:Number(v)}))}]};});}
  private educationChoices():ActionChoice[]{const defs=[['数理工科','把时间押在数理、工程与技术上','intelligence'],['医学路线','进入漫长而严格的医学训练','discipline'],['艺术传媒','把表达与审美当成职业筹码','happiness'],['警校路线','选择秩序、纪律与公共责任','stability']] as [string,string,StatKey][];return defs.map(([v,d,k])=>({id:`edu:${v}`,sourceEvent:'education',category:'教育',title:v,desc:d,hint:'会影响未来职业池，但不会锁死转行',outcomes:[{weight:1,text:`你选择了${v}。`,tone:'neutral',ops:[{type:'education',value:v},{type:'tag',tag:v},{type:'stat',key:k,delta:7}]}]}));}
  private careerChoices():ActionChoice[]{const s=this.store.get();let routes=[...this.base.CAREER_ROUTES];if(/数理|工程/.test(s.education))routes=routes.filter(r=>['科技','游戏','工程','科研','制造'].includes(r.group));else if(/医学/.test(s.education))routes=routes.filter(r=>['医疗','科研'].includes(r.group));else if(/艺术/.test(s.education))routes=routes.filter(r=>['创意','演艺','内容','传媒','游戏'].includes(r.group));else if(/警校/.test(s.education))routes=routes.filter(r=>['公共','法律','交通'].includes(r.group));if(routes.length<4)routes=[...this.base.CAREER_ROUTES];return this.rng.shuffle(routes).slice(0,4).map(r=>({id:`career:${r.id}`,sourceEvent:'career_start',category:'职业',title:`${r.icon} ${r.titles[0]}`,desc:`进入${r.group}路线，从第一阶开始。`,hint:`这条路线一共有 ${r.titles.length} 阶，可以晋升也可以转行。`,outcomes:[{weight:1,text:`你进入了${r.titles[0]}岗位。`,tone:'neutral',ops:[{type:'careerSet',route:r.id,level:1}]}]}));}
  private fallbacks():ActionChoice[]{return[
    {id:'fb:rest',sourceEvent:'fallback',category:'生活',title:'给自己留一点空白',desc:'少做一些事，看看精神状态会不会回来。',hint:'恢复，但可能错过机会',outcomes:[{weight:1,text:'这一年没有大突破，但你重新找回了一些呼吸感。',tone:'good',ops:[{type:'stat',key:'happiness',delta:6},{type:'stat',key:'health',delta:2}]}]},
    {id:'fb:skill',sourceEvent:'fallback',category:'成长',title:'学一个真正会用到的技能',desc:'不是为了证书，而是为了让自己多一条路。',hint:'长期能力积累',outcomes:[{weight:1,text:'你没有立刻变强很多，但这项技能后来多次派上用场。',tone:'good',ops:[{type:'stat',key:'intelligence',delta:5},{type:'stat',key:'discipline',delta:3}]}]},
    {id:'fb:network',sourceEvent:'fallback',category:'社交',title:'去一个陌生圈子认识人',desc:'你不知道会碰到谁。',hint:'可能扩展关系网',outcomes:[{weight:1,text:'你认识了几张新面孔，其中一两个人后来又出现过。',tone:'neutral',ops:[{type:'stat',key:'social',delta:4}]}]},
    {id:'fb:health',sourceEvent:'fallback',category:'健康',title:'认真处理一个拖了很久的身体问题',desc:'不再靠“应该没事”来处理健康。',hint:'降低长期风险',outcomes:[{weight:1,text:'问题没有奇迹般消失，但你至少开始认真处理它。',tone:'good',ops:[{type:'stat',key:'health',delta:6}]}]}
  ];}
  private eligibleLegacy(e:LegacyEvent){const s=this.store.get();if(s.age<e.minAge||s.age>e.maxAge||!passes(s,requirement(e.requires)))return false;const seen=s.seen[e.id];if(seen!=null){if(!e.repeatable)return false;if(s.age-seen<(e.cooldown??4))return false;}if(e.category==='投资'&&!s.tags.includes('投资者'))return false;return true;}
  async draftChoices():Promise<ActionChoice[]>{const s=this.store.get();if(!s.alive)return[];if(s.age===1)return this.zhouChoices();if(this.fate.isDue()){if(!s.fate.snapshotKey)await this.fate.capture();return this.fate.choices();}if(s.age===18)return this.educationChoices();if(s.age===22&&!s.careerRoute)return this.careerChoices();const events=(await this.content.events(s.age)).filter(e=>this.eligibleLegacy(e));const picked:ActionChoice[]=[];for(const e of this.rng.shuffle(events)){const c=eventToChoice(e,s,this.rng);if(c)picked.push(c);if(picked.length>=4)break;}for(const f of this.rng.shuffle(this.fallbacks())){if(picked.length>=4)break;picked.push(f);}let choices=picked.slice(0,4);const promo=this.career.promotionChoice();if(promo&&this.rng.next()<.35)choices[this.rng.int(0,3)]=promo;choices=this.relationships.inject(choices);return choices;}
  async ensureChoices(){if(this.store.get().alive&&this.store.get().currentChoices.length===0)this.store.dispatch({type:'SET_CHOICES',choices:await this.draftChoices()});}
  private pickOutcome(c:ActionChoice):Outcome{const s=this.store.get();return this.rng.weighted(c.outcomes,o=>{let w=Math.max(.01,o.weight);if(o.tone==='good')w*=1+(s.stats.luck-50)*.004+(s.stats.discipline-50)*.0015;if(o.tone==='bad')w*=1-(s.stats.luck-50)*.002;return Math.max(.05,w)});}
  private microStory():HistoryEntry|null{const s=this.store.get();const bank=[
    {min:8,max:90,title:'🚗 路边一个急刹车把你吓清醒了',text:'你差点和一辆没注意到你的车撞上。最后只是擦伤，但这一瞬间足够让人重新尊重概率。',tone:'bad' as Tone,ops:[{type:'stat',key:'health',delta:-3} as const]},
    {min:16,max:75,title:'📱 你把一句吐槽发进了不该发的群',text:'撤回速度很快，截图速度更快。好消息是世界没毁灭，坏消息是你获得了一个新的睡前回忆。',tone:'bad' as Tone,ops:[{type:'stat',key:'happiness',delta:-2} as const,{type:'stat',key:'social',delta:-2} as const]},
    {min:18,max:85,title:'🍜 一顿普通饭局意外聊出了新东西',text:'本来只是填饱肚子，最后却听到一个后来真的派上用场的信息。',tone:'good' as Tone,ops:[{type:'stat',key:'luck',delta:2} as const,{type:'stat',key:'social',delta:2} as const]},
    {min:20,max:90,title:'📦 快递送错楼层，你认识了一个邻居',text:'你们花了几分钟确认谁的包裹是谁的。事情很小，但城市里又多了一张熟脸。',tone:'neutral' as Tone,ops:[{type:'stat',key:'social',delta:1} as const]},
    {min:22,max:65,title:'🧑‍💻 AI 一本正经地给了你一个错误答案',text:'你差点照做，幸好最后多查了一步。技术很强，核验也仍然值钱。',tone:'neutral' as Tone,ops:[{type:'stat',key:'intelligence',delta:2} as const,{type:'stat',key:'discipline',delta:1} as const]},
    {min:25,max:70,title:'🦷 牙齿用疼痛提醒你它也属于身体',text:'拖了很久的问题终于逼你去处理。钱包和健康同时受到了一点教育。',tone:'bad' as Tone,ops:[{type:'stat',key:'health',delta:-2} as const,{type:'money',source:'incident',label:'临时医疗支出',amount:-1800} as const]},
    {min:30,max:90,title:'☔ 一场大雨让当天计划全部重排',text:'你没有完成原来的安排，却意外获得了一段久违的空白时间。',tone:'neutral' as Tone,ops:[{type:'stat',key:'happiness',delta:2} as const]},
    {min:40,max:95,title:'🪜 你突然发现有些动作不再像年轻时那么轻松',text:'不是疾病，只是身体很诚实地更新了版本说明。',tone:'neutral' as Tone,ops:[{type:'stat',key:'health',delta:-1} as const]}
  ];const e=this.rng.pick(bank.filter(x=>s.age>=x.min&&s.age<=x.max));if(!e)return null;const pseudo:ActionChoice={id:'micro',sourceEvent:'micro',category:'生活',title:e.title,desc:e.text,outcomes:[]};const out:Outcome={weight:1,text:e.text,tone:e.tone,ops:[...e.ops] as any};applyOutcomeOps(this.store,pseudo,out,this.relationships,this.career);return{age:s.age,title:e.title,text:e.text,tone:e.tone,kind:'incident',changes:'生活又把轨迹拨动了一点',sourceId:'micro'};}
  private changes(before:GameState,after:GameState){const parts:string[]=[];for(const k of statKeys){const d=after.stats[k]-before.stats[k];if(Math.abs(d)>=2)parts.push(`${this.base.ATTR[k]?.name??k}${d>0?'有所提升':'有所下降'}`)}const mw=after.wealth-before.wealth;if(Math.abs(mw)>=100)parts.push(`财富${mw>0?'+':''}${Math.round(mw/1000)/10}万`);return parts.slice(0,4).join(' · ')||'没有明显变化';}
  async resolve(index:number){const s0=this.store.get();if(s0.ui.busy||!s0.alive)return;const choice=s0.currentChoices[index];if(!choice||!passes(s0,choice.requires))return;const before=this.store.snapshot();this.store.dispatch({type:'UI_BUSY',value:true});try{
      this.money.begin();const out=this.pickOutcome(choice);applyOutcomeOps(this.store,choice,out,this.relationships,this.career);if(choice.sourceEvent==='lachesis')this.fate.commit(String(choice.meta?.fateBranch??'unknown'));const s1=this.store.get();this.store.dispatch({type:'SEEN',id:choice.sourceEvent,age:s1.age});const hist:HistoryEntry={age:s1.age,title:choice.title,text:out.text,tone:out.tone??'neutral',kind:choice.rare?'rare':'choice',changes:this.changes(before,this.store.snapshot()),sourceId:choice.sourceEvent};this.store.dispatch({type:'HISTORY',entry:hist});
      this.world.tick();this.career.tick();this.relationships.tick();const extraCount=this.rng.next()<.43?0:this.rng.next()<.76?1:2;for(let i=0;i<extraCount&&this.store.get().yearStories.length<3;i++){const m=this.microStory();if(m)this.store.dispatch({type:'HISTORY',entry:m});}this.money.annual();const died=this.mortality.check();const snap=this.store.snapshot();snap.score=scoreState(snap);snap.careerPeak=Math.max(snap.careerPeak,snap.careerLevel);this.store.replace(snap);
      if(!died){this.store.dispatch([{type:'ADVANCE_AGE'},{type:'SET_CHOICES',choices:[]}]);this.store.dispatch({type:'SET_CHOICES',choices:await this.draftChoices()});}
      await this.persist.save(this.store.snapshot());
    }catch(e){console.error('[V7] yearly transaction rollback',e);this.store.replace(before);this.store.dispatch({type:'UI_MESSAGE',value:'这一年处理异常，已完整回滚。'});}finally{this.store.dispatch({type:'UI_BUSY',value:false});}
  }
  async rewindFate(){const ok=await this.fate.rewind();if(ok){this.store.dispatch({type:'SET_CHOICES',choices:this.fate.choices()});await this.persist.save(this.store.snapshot());}return ok;}
}
