import type {BaseContent,GameState,Relationship,StatKey} from './types.js';
import type {GameRuntime} from './engine.js';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const money=(n:number)=>{const a=Math.abs(n),sign=n<0?'-':'';if(a>=100000000)return`${sign}¥${(a/100000000).toFixed(2)}亿`;if(a>=10000)return`${sign}¥${(a/10000).toFixed(1)}万`;return`${sign}¥${Math.round(a)}`};
const icon:Record<StatKey,string>={health:'❤️',happiness:'☀️',intelligence:'🧠',social:'🗣️',luck:'🍀',ambition:'🔥',stability:'🛡️',discipline:'⏱️',risk:'🎲',family:'🏠'};
const label=(k:StatKey,v:number)=>{const banks:Record<StatKey,string[]>={health:['很虚弱','状态欠佳','普通','结实','非常强健','近乎离谱'],happiness:['低落','有些疲惫','平常','满足','很幸福','近乎通透'],intelligence:['吃力','普通','不错','敏锐','非常出众','怪物级'],social:['疏离','偏安静','普通','会来事','人脉很强','走到哪都有人'],luck:['诸事不顺','一般','偶有顺风','比较走运','非常走运','像开了命运挂'],ambition:['佛系','普通','有目标','很有野心','野心极强','想把桌子掀了'],stability:['容易波动','一般','还算稳定','抗压很强','非常稳','几乎不可撼动'],discipline:['散漫','普通','能坚持','很自律','长期主义','像机器一样稳定'],risk:['极度谨慎','偏谨慎','普通','敢下注','非常激进','拿命写赔率'],family:['非常疏远','有距离','普通','亲近','非常紧密','像一个共同体']};const i=v<35?0:v<55?1:v<80?2:v<110?3:v<150?4:5;return banks[k][i]!;};
const roleClass=(r:Relationship)=>r.alive===false?'dead':r.role==='伴侣'?'partner':r.role==='仇人'||r.role==='对头'?'hostile':'';

export class UI{
  private root:HTMLElement;private mode:'start'|'play'='play';
  constructor(private runtime:GameRuntime,root:HTMLElement){this.root=root;this.bind();}
  setStart(v:boolean){this.mode=v?'start':'play';this.render();}
  private bind(){this.root.addEventListener('click',async e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!el)return;const a=el.dataset.action;try{
      if(a==='reroll'){await this.runtime.reroll();this.mode='start';this.render();}
      else if(a==='begin'){this.mode='play';this.render();}
      else if(a==='choice'){await this.runtime.resolve(Number(el.dataset.index));this.render();}
      else if(a==='view'){this.runtime.store.dispatch({type:'UI_VIEW',view:(el.dataset.view as any)||'game'});this.render();}
      else if(a==='fresh'){await this.runtime.reroll();this.mode='start';this.render();}
      else if(a==='rewind'){if(await this.runtime.rewindFate()){this.mode='play';this.render();}}
      else if(a==='save'){await this.runtime.persist.save(this.runtime.store.snapshot());this.runtime.store.dispatch({type:'UI_MESSAGE',value:'已保存到 IndexedDB'});this.render();}
    }catch(err){console.error(err);}
  });}
  render(){if(this.mode==='start'){this.root.innerHTML=this.start();return;}const s=this.runtime.store.get();this.root.innerHTML=!s.alive?this.end():s.ui.view==='info'?this.info():this.game();}
  private start(){const s=this.runtime.store.get(),traits=s.traits.map(t=>`<span class="trait r-${esc(t.rarity)}">${esc(t.name)}</span>`).join('');return`<section class="start shell"><div class="logo"><div class="avatar">${this.runtime.avatarEmoji(s.avatar)}</div><div><h1>人生随机实验室</h1><p>V7 · Engine Rewrite</p></div></div><div class="opening"><article><small>🌐 出生时代</small><strong>${esc(s.worldName)}</strong><span>${esc(s.background)}</span></article><article><small>🎭 主角</small><strong>${esc(s.gender)} · 随机身份</strong><span>所有后台能力都保持黑箱，只给你现实能感知到的信息。</span></article></div><div class="open-traits"><div class="section"><strong>开局随机词条 ×5</strong><span>可以继续 Roll</span></div>${traits}</div><div class="engine-note"><b>V7 新发动机</b><span>事件、钱、职业、关系、世界、死亡和命运都已拆成独立系统；存档改用 IndexedDB。</span></div><div class="start-actions"><button data-action="reroll">🎲 再 Roll 一次</button><button class="primary" data-action="begin">就这把，开始 →</button></div></section>`;}
  private hud(s:Readonly<GameState>){const r=this.runtime.base.CAREER_ROUTES.find(x=>x.id===s.careerRoute),partner=s.relationships.find(x=>x.id===s.partnerId&&x.alive);const traits=s.traits.slice(0,5).map(t=>`<span class="trait r-${esc(t.rarity)}">${esc(t.name)}</span>`).join('');return`<section class="hud"><div class="hero"><div class="avatar">${this.runtime.avatarEmoji(s.avatar)}</div><div><strong>${s.age} 岁</strong><span>${esc(s.gender)} · ${esc(r?.titles[s.careerLevel-1]??'待业')}</span><b>${money(s.wealth)}</b></div></div><div class="toptraits">${traits}</div>${partner?`<div class="partner-mini"><div class="avatar">${this.runtime.avatarEmoji(partner.avatar)}</div><div><small>💞 伴侣</small><strong>${esc(partner.name)} · ${Math.max(18,s.age-partner.ageGap)}岁</strong><span>${esc(this.runtime.base.CAREER_ROUTES.find(x=>x.id===partner.careerRoute)?.titles[partner.careerLevel-1]??'自由职业')}</span></div></div>`:''}</section>`;}
  private finance(s:Readonly<GameState>){const l=s.ledger;if(!l||!l.items.length)return'';return`<section class="ledger"><div><strong>💰 ${s.age-1} 岁财富账本</strong><b class="${l.net>=0?'good':'bad'}">${l.net>=0?'+':''}${money(l.net)}</b></div><p>${l.items.map(x=>`${esc(x.label)} ${x.amount>0?'+':''}${money(x.amount)}`).join(' · ')}</p></section>`;}
  private states(s:Readonly<GameState>){return`<section class="states"><div class="section"><strong>身体与状态</strong><span>只显示体感，不公开刻度</span></div><div class="state-grid">${(Object.keys(s.stats) as StatKey[]).map(k=>`<div class="state"><span>${icon[k]} ${esc(this.runtime.base.ATTR[k]?.name??k)}</span><b>${label(k,s.stats[k])}</b></div>`).join('')}</div></section>`;}
  private stories(s:Readonly<GameState>){return`<section class="stories"><div class="section"><strong>最新人生轨迹</strong><span>${s.yearStories.length?`${s.yearStories[0]!.age} 岁 · ${s.yearStories.length}件事`:'尚未落笔'}</span></div><div class="story-box">${s.yearStories.length?s.yearStories.slice(0,3).map((h,i)=>`<article class="${h.tone}"><b>${i+1}. ${esc(h.title)}</b><p>${esc(h.text)}</p><small>${esc(h.changes??'')}</small></article>`).join('<hr>'):'<p>选择今年的一件事。系统会把真正发生的结果写在这里。</p>'}</div></section>`;}
  private world(s:Readonly<GameState>){return`<section class="world"><div><strong>🌐 时代风向</strong><span>${esc(s.world.headline)}</span></div><div class="world-tags"><i>经济 ${s.world.economy>60?'景气':s.world.economy<40?'承压':'平稳'}</i><i>就业 ${s.world.jobs>60?'旺':s.world.jobs<40?'冷':'稳'}</i><i>科技 ${s.world.tech>70?'跃迁':s.world.tech>50?'活跃':'平静'}</i><i>市场 ${s.world.market>60?'偏强':s.world.market<40?'偏弱':'震荡'}</i></div></section>`;}
  private choices(s:Readonly<GameState>){return`<section class="choice-wrap"><div class="section"><strong>${s.fate.targetAge===s.age&&!s.fate.triggered?'✦ 拉刻西斯节点 · 宿命奇点':'这一年，你把主要精力押在哪里？'}</strong><span>${s.currentChoices.length} 选 1</span></div><div class="choices">${s.currentChoices.map((c,i)=>`<button data-action="choice" data-index="${i}" ${s.ui.busy?'disabled':''} class="${c.rare?'rare':''}"><small>${esc(c.category)}</small><strong>${esc(c.title)}</strong><p>${esc(c.desc)}</p><em>${esc(c.hint??'结果会被经历、时代和运气共同改写。')}</em></button>`).join('')}</div></section>`;}
  private nav(view:'game'|'info'){return`<nav><button data-action="view" data-view="game" class="${view==='game'?'active':''}">🎮 游戏进程</button><button data-action="view" data-view="info" class="${view==='info'?'active':''}">🧬 人物信息</button></nav>`;}
  private game(){const s=this.runtime.store.get();return`<main class="shell game">${this.hud(s)}${this.finance(s)}${this.states(s)}${this.world(s)}${this.stories(s)}${this.choices(s)}${this.nav('game')}</main>`;}
  private info(){const s=this.runtime.store.get(),route=this.runtime.base.CAREER_ROUTES.find(x=>x.id===s.careerRoute);return`<main class="shell info">${this.hud(s)}<section class="panel"><div class="section"><strong>🧳 职业路线</strong><span>${route?`${s.careerLevel}/5 阶`:'尚未进入'}</span></div>${route?`<div class="ladder">${route.titles.map((x,i)=>`<div class="${i+1===s.careerLevel?'now':i+1<s.careerLevel?'done':''}"><b>${i+1}</b><span>${esc(x)}</span><small>${money(route.salaries[i]!)}/月</small></div>`).join('')}</div>`:'<p>毕业、转行和机会会把你带进一条职业路线。</p>'}</section>${this.relationshipPanel(s)}<section class="panel"><div class="section"><strong>🏷️ 词条</strong><span>${s.traits.length} 个</span></div><div class="traits">${s.traits.map(t=>`<span class="trait r-${esc(t.rarity)}">${esc(t.name)}</span>`).join('')}</div></section><section class="panel"><div class="section"><strong>📜 完整人生轨迹</strong><span>${s.history.length} 条</span></div><div class="history">${s.history.slice(0,160).map(h=>`<article class="${h.tone}"><b>${h.age} 岁 · ${esc(h.title)}</b><p>${esc(h.text)}</p></article>`).join('')}</div></section><section class="panel"><div class="section"><strong>💾 存档</strong><span>IndexedDB</span></div><button data-action="save">立即保存</button></section>${this.nav('info')}</main>`;}
  private relationshipPanel(s:Readonly<GameState>){const list=[...s.relationships].sort((a,b)=>(b.role==='伴侣'?1000:0)+b.affinity*5+b.sharedEvents*8-((a.role==='伴侣'?1000:0)+a.affinity*5+a.sharedEvents*8));return`<section class="panel network"><div class="section"><strong>🕸️ 关系网</strong><span>在世 ${list.filter(x=>x.alive).length} · 已故 ${list.filter(x=>!x.alive).length}</span></div>${list.length?`<div class="rel-grid">${list.slice(0,20).map(r=>{const cr=this.runtime.base.CAREER_ROUTES.find(x=>x.id===r.careerRoute);return`<article class="rel ${roleClass(r)}"><div><div class="avatar">${this.runtime.avatarEmoji(r.avatar)}</div><strong>${esc(r.name)}</strong><b>${r.alive?r.role:'已故'}</b></div><span>${esc(r.gender)} · ${r.alive?`${Math.max(18,s.age-r.ageGap)}岁`:`享年${r.deathAge??'?'}岁`} · ${esc(cr?.titles[r.careerLevel-1]??'普通工作')}</span><small>相识于你${r.metAge}岁 · ${r.sharedEvents}次交集 · ${r.affinity>=70?'非常亲近':r.affinity>=35?'亲近':r.affinity>=0?'普通':r.affinity>-45?'紧张':'敌对'}</small><p>${esc(r.history[0]?.text??'这一年没有特别变化。')}</p></article>`}).join('')}</div>`:'<p>18 岁以后，偶遇、共事、冲突与长期往来会把人逐渐写进这里。</p>'}</section>`;}
  private end(){const s=this.runtime.store.get(),after=this.runtime.relationships.afterlives(),rank=s.score>2200?'SSR':s.score>1800?'SS':s.score>1400?'S':s.score>1000?'A':'B';const peak=s.financeHistory.reduce((m,x)=>Math.max(m,x.closing),s.wealthPeak);return`<main class="shell ending"><section class="end-hero"><span>${rank}</span><div><h1>${s.age} 岁 · ${esc(s.deathReason)}</h1><p>世界线 ${s.fate.worldline} · 人生综合分 ${s.score}</p></div></section><section class="metrics"><div><small>最终财富</small><strong>${money(s.wealth)}</strong></div><div><small>财富峰值</small><strong>${money(peak)}</strong></div><div><small>职业峰值</small><strong>${s.careerPeak}/5</strong></div><div><small>关系网</small><strong>${s.relationships.length} 人</strong></div></section><section class="panel verdict"><div class="section"><strong>📜 这一生</strong><span>不是只看终点</span></div>${this.verdict(s).map(x=>`<p>${esc(x)}</p>`).join('')}</section>${s.fate.triggered&&s.fate.snapshotKey?`<section class="panel fate-end"><strong>✦ 拉刻西斯节点 · 宿命奇点</strong><p>${s.fate.targetAge} 岁，你选择了「${esc(s.fate.branch??'未知')}」。很多后来的事件，从这里开始换了轨道。</p><button data-action="rewind">↶ 回到 ${s.fate.targetAge} 岁，走另一条人生</button></section>`:''}<section class="panel after"><div class="section"><strong>🕯️ 你死之后，他们继续活着</strong><span>最深的 ${after.length} 段关系</span></div>${after.map(r=>`<article><b>${esc(r.name)} · ${esc(r.role)}</b><p>${esc((r as any).epilogue)}</p></article>`).join('')}</section><div class="end-actions"><button data-action="fresh">全新人生</button></div></main>`;}
  private verdict(s:Readonly<GameState>){const lines:string[]=[];const route=this.runtime.base.CAREER_ROUTES.find(x=>x.id===s.careerRoute);lines.push(`你从「${s.background}」出发，走到 ${s.age} 岁。最后的身份是${route?.titles[s.careerLevel-1]??'普通人'}，这局一共留下 ${s.history.length} 条被系统记住的轨迹。`);if(s.wealth<0)lines.push('钱这条线打得不漂亮，最终仍在负债区。但每一笔增减都能在年度账本里找到来源，不再有后台凭空跳钱。');else if(s.wealthPeak>5_000_000)lines.push('你确实把财富推到了很高的位置。真正稀有的不是见过大数字，而是有没有把它留到最后。');else lines.push('财富没有变成唯一主角。你拥有过选择权，也为很多现实成本持续买单。');if(s.relationships.length>=6)lines.push(`你的一生不是单人剧。关系网里出现过 ${s.relationships.length} 个人，其中 ${s.relationships.filter(x=>!x.alive).length} 人先你离开。`);if(s.fate.triggered)lines.push(`如果一定要找一个“从这里开始不一样”的年份，${s.fate.targetAge} 岁的拉刻西斯节点最接近答案。`);lines.push(s.age>90?'你活得足够久，年轻时很多所谓长期问题最后都被你亲自熬成了短期问题。':'你没拿到完整攻略，但大多数年份还是一边猜一边往前走了。');return lines;}
}
