import type {ActionChoice,GameState,HistoryEntry,Relationship,Requirement,StatKey,TraitRef} from './types.js';
import type {GameRuntime} from './engine.js';
import {passes} from './content.js';
import {routeDef,synergyName,traitDisplayName} from './builds.js';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const money=(n:number)=>{const a=Math.abs(n),sign=n<0?'-':'';if(a>=100000000)return`${sign}¥${(a/100000000).toFixed(2)}亿`;if(a>=10000)return`${sign}¥${(a/10000).toFixed(1)}万`;return`${sign}¥${Math.round(a)}`};
const statKeys:StatKey[]=['health','happiness','intelligence','social','luck','ambition','stability','discipline','risk','family'];
const icon:Record<StatKey,string>={health:'♥',happiness:'☀',intelligence:'◆',social:'●',luck:'✦',ambition:'▲',stability:'■',discipline:'⌁',risk:'◇',family:'⌂'};
const label=(k:StatKey,v:number)=>{const banks:Record<StatKey,string[]>={health:['很虚弱','状态欠佳','普通','结实','非常强健','近乎离谱'],happiness:['低落','有些疲惫','平常','满足','很幸福','近乎通透'],intelligence:['吃力','普通','不错','敏锐','非常出众','怪物级'],social:['疏离','偏安静','普通','会来事','人脉很强','走到哪都有人'],luck:['诸事不顺','一般','偶有顺风','比较走运','非常走运','像开了命运挂'],ambition:['佛系','普通','有目标','很有野心','野心极强','想把桌子掀了'],stability:['容易波动','一般','还算稳定','抗压很强','非常稳','几乎不可撼动'],discipline:['散漫','普通','能坚持','很自律','长期主义','像机器一样稳定'],risk:['极度谨慎','偏谨慎','普通','敢下注','非常激进','拿命写赔率'],family:['非常疏远','有距离','普通','亲近','非常紧密','像一个共同体']};const i=v<35?0:v<55?1:v<80?2:v<110?3:v<150?4:5;return banks[k][i]!;};
const roleClass=(r:Relationship)=>r.alive===false?'dead':r.role==='伴侣'?'partner':r.role==='仇人'||r.role==='对头'?'hostile':'';

export class UI{
  private root:HTMLElement;private mode:'start'|'play'='play';private openChoice:number|null=null;
  constructor(private runtime:GameRuntime,root:HTMLElement){this.root=root;this.bind();}
  setStart(v:boolean){this.mode=v?'start':'play';this.openChoice=null;this.render();}
  private bind(){this.root.addEventListener('click',async e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!el)return;const a=el.dataset.action;try{
      if(a==='reroll'){await this.runtime.reroll();this.mode='start';this.openChoice=null;this.render();}
      else if(a==='begin'){this.mode='play';this.openChoice=null;this.render();}
      else if(a==='choice'){const i=Number(el.dataset.index),c=this.runtime.store.get().currentChoices[i];if(c?.responses?.length){this.openChoice=i;this.render();}else{await this.runtime.resolve(i);this.openChoice=null;this.render();}}
      else if(a==='response'){await this.runtime.resolve(Number(el.dataset.index),Number(el.dataset.response));this.openChoice=null;this.render();}
      else if(a==='close-response'){this.openChoice=null;this.render();}
      else if(a==='view'){this.openChoice=null;this.runtime.store.dispatch({type:'UI_VIEW',view:(el.dataset.view as any)||'game'});this.render();}
      else if(a==='fast'){const s=this.runtime.store.get();this.runtime.store.dispatch({type:'UI_FAST',value:!s.ui.fast});this.render();}
      else if(a==='fresh'){await this.runtime.reroll();this.mode='start';this.openChoice=null;this.render();}
      else if(a==='rewind'){if(await this.runtime.rewindFate()){this.mode='play';this.openChoice=null;this.render();}}
      else if(a==='save'){await this.runtime.persist.save(this.runtime.store.snapshot());this.runtime.store.dispatch({type:'UI_MESSAGE',value:'已保存到 IndexedDB'});this.render();}
    }catch(err){console.error(err);}
  });}
  render(){const s=this.runtime.store?.get();this.root.classList.toggle('fast-ui',!!s?.ui.fast);if(this.mode==='start'){this.root.innerHTML=this.start();return;}if(!s)return;this.root.innerHTML=!s.alive?this.end():s.ui.view==='info'?this.info():s.ui.view==='collection'?this.collection():this.game();}

  private traitDef(t:TraitRef){return(this.runtime.base.TRAITS as any[]).find(x=>x.id===t.id);}
  private rarityName(rarity:string){return String(this.runtime.base.RARITY?.[rarity]?.name??rarity);}
  private traitPill(t:TraitRef){const desc=t.desc??String(this.traitDef(t)?.desc??'这个词条会参与你的人生构筑。'),name=traitDisplayName(t);return`<span class="trait r-${esc(t.rarity)} ${t.level&&t.level>1?'evolved':''}" title="${esc(desc)}"><i>${esc(this.rarityName(t.rarity))}</i><b>${esc(name)}</b></span>`;}
  private traitCard(t:TraitRef){const desc=t.evolutionText??t.desc??String(this.traitDef(t)?.desc??'这个词条会参与你的人生构筑。'),name=traitDisplayName(t);return`<article class="trait-card r-${esc(t.rarity)} ${t.level&&t.level>1?'evolved':''}"><div class="trait-rarity">${t.level&&t.level>1?'进化 · ':''}${esc(this.rarityName(t.rarity))}</div><strong>${esc(name)}</strong><p>${esc(desc)}</p></article>`;}
  private statTiles(s:Readonly<GameState>,opening=false){return`<div class="state-grid ${opening?'opening-state-grid':''}">${statKeys.map(k=>`<div class="state" title="${esc(this.runtime.base.ATTR[k]?.tip??'')}"><span><i>${icon[k]}</i>${esc(this.runtime.base.ATTR[k]?.name??k)}</span><b>${label(k,s.stats[k])}</b>${opening?'<small>数值隐藏</small>':''}</div>`).join('')}</div>`;}
  private familyResource(v:number){return v<35?'资源紧张':v<50?'偏紧':v<68?'普通':v<82?'宽裕':'资源充足';}
  private synergyStrip(s:Readonly<GameState>){if(!s.synergies.length)return'';return`<section class="synergy-strip"><div><small>BUILD ONLINE</small><strong>构筑已经开始咬合</strong></div><div>${s.synergies.slice(0,5).map(y=>`<span title="${esc(y.desc)}">${esc(y.name)} <b>×${y.tier}</b></span>`).join('')}</div></section>`;}

  private start(){const s=this.runtime.store.get(),originTag=s.tags[0]??'普通出身',personality=s.tags[1]??'性格未定',talent=s.tags[2]??'天赋未显',flaw=s.tags[3]??'缺陷未显';return`<section class="start shell">
    <header class="start-hero"><div class="start-avatar">${this.runtime.avatarEmoji(s.avatar)}</div><div><span class="eyebrow">LIFE / STAGE · NEW RUN</span><h1>人生随机实验室</h1><p>一套会在几十年里相互咬合、进化并留下后果的构筑。</p></div></header>
    <section class="origin-grid">
      <article class="origin-card era"><small>🌐 出生时代</small><strong>${esc(s.worldName)}</strong><p>大环境持续改写就业、科技、市场与机会密度。</p></article>
      <article class="origin-card family"><small>🏠 家庭底色</small><strong>${esc(s.background)}</strong><p>${esc(originTag)} · 家庭资源：${this.familyResource(s.familyResources)}。这是家庭条件，不是你的个人存款。</p></article>
      <article class="origin-card personality"><small>🫀 性格底色</small><strong>${esc(personality)}</strong><p>决定你在长期选择中更容易偏向哪一边。</p></article>
      <article class="origin-card talent"><small>✦ 天赋</small><strong>${esc(talent)}</strong><p>让某些路线更顺，但不会替你自动通关。</p></article>
      <article class="origin-card flaw"><small>⚠ 缺陷</small><strong>${esc(flaw)}</strong><p>弱点不会消失，只会在错误的年份突然收费。</p></article>
    </section>
    ${s.runFlags.echo?`<section class="echo-opening"><small>PREVIOUS LIFE ECHO</small><strong>前世回响 · ${esc(s.runFlags.echo)}</strong><p>它不会直接送属性，只可能在某个成长节点给你一丝似曾相识的直觉。</p></section>`:''}
    <section class="opening-stats"><div class="section"><div><strong>十维底层能力</strong><p>十个维度统一视觉，只告诉你体感，不公开后台精确数值。</p></div><span>BLACK BOX × 10</span></div>${this.statTiles(s,true)}</section>
    <section class="open-traits"><div class="section"><div><strong>命格词条 ×${s.traits.length}</strong><p>这些词条现在会真正进入判定、收入、稀有事件、寿命和隐藏路线。</p></div><span>可继续 Roll</span></div><div class="trait-card-grid">${s.traits.map(t=>this.traitCard(t)).join('')}</div></section>
    ${this.synergyStrip(s)}
    <div class="start-actions"><button data-action="reroll">🎲 重开命盘</button><button class="primary" data-action="begin">接受这条世界线 →</button></div>
  </section>`;}

  private hud(s:Readonly<GameState>){const r=this.runtime.base.CAREER_ROUTES.find(x=>x.id===s.careerRoute),partner=s.relationships.find(x=>x.id===s.partnerId&&x.alive);const traits=s.traits.slice(0,6).map(t=>this.traitPill(t)).join('');return`<section class="hud"><div class="hero"><div class="avatar">${this.runtime.avatarEmoji(s.avatar)}</div><div><strong>${s.age} 岁</strong><span>${esc(s.gender)} · ${esc(r?.titles[s.careerLevel-1]??(s.age<18?'未成年':'待业'))}</span><b>${s.age<18?'个人资产 '+money(s.wealth):money(s.wealth)}</b></div></div><div class="toptraits">${traits}</div>${partner?`<div class="partner-mini"><div class="avatar">${this.runtime.avatarEmoji(partner.avatar)}</div><div><small>💞 伴侣</small><strong>${esc(partner.name)} · ${Math.max(18,s.age-partner.ageGap)}岁</strong><span>${esc(this.runtime.base.CAREER_ROUTES.find(x=>x.id===partner.careerRoute)?.titles[partner.careerLevel-1]??'自由职业')}</span></div></div>`:''}</section>`;}
  private finance(s:Readonly<GameState>){const l=s.ledger;if(!l||!l.items.length)return'';return`<section class="ledger"><div><strong>💰 ${s.age-1} 岁财富账本</strong><b class="${l.net>=0?'good':'bad'}">${l.net>=0?'+':''}${money(l.net)}</b></div><p>${l.items.map(x=>`${esc(x.label)} ${x.amount>0?'+':''}${money(x.amount)}`).join(' · ')}</p></section>`;}
  private states(s:Readonly<GameState>){return`<section class="states"><div class="section"><div><strong>身体与状态</strong><p>统一样式、数值黑箱；真正的差异体现在可选项和结果里。</p></div><span>10 DIMENSIONS</span></div>${this.statTiles(s)}</section>`;}
  private visibleStories(s:Readonly<GameState>):HistoryEntry[]{if(s.yearStories.length)return s.yearStories.slice(0,3);const lastAge=s.history[0]?.age;if(lastAge==null)return[];return s.history.filter(h=>h.age===lastAge).slice(0,3).sort((a,b)=>Number(!(a.kind==='choice'||a.kind==='rare'||a.kind==='evolution'))-Number(!(b.kind==='choice'||b.kind==='rare'||b.kind==='evolution')));}
  private stories(s:Readonly<GameState>){const stories=this.visibleStories(s),prismatic=stories.some(h=>h.rarity==='prismatic'||h.sourceId==='lachesis'||h.kind==='evolution');return`<section class="stories ${prismatic?'special-story':''}"><div class="section"><div><strong>${prismatic?'✦ 稀有结果已发生':'最新人生轨迹'}</strong><p>${prismatic?'彩色只在真正稀有的结果发生之后出现。':'刚刚做出的选择必须在这里留下真实结果。'}</p></div><span>${stories.length?`${stories[0]!.age} 岁 · ${stories.length}件事`:'尚未落笔'}</span></div><div class="story-box">${stories.length?stories.map((h,i)=>`<article data-story="1" class="${h.tone} rarity-${h.rarity??'normal'} ${h.kind==='evolution'?'evolution-story':''}"><b>${i+1}. ${esc(h.title)}</b><p>${esc(h.text)}</p><small>${esc(h.changes??'')}</small></article>`).join('<hr>'):'<p class="story-empty">选择今年的一件事。结果不会再被年龄推进清空。</p>'}</div></section>`;}
  private world(s:Readonly<GameState>){return`<section class="world"><div><strong>🌐 时代风向</strong><span>${esc(s.world.headline)}</span></div><div class="world-tags"><i>经济 ${s.world.economy>60?'景气':s.world.economy<40?'承压':'平稳'}</i><i>就业 ${s.world.jobs>60?'旺':s.world.jobs<40?'冷':'稳'}</i><i>科技 ${s.world.tech>70?'跃迁':s.world.tech>50?'活跃':'平静'}</i><i>市场 ${s.world.market>60?'偏强':s.world.market<40?'偏弱':'震荡'}</i></div></section>`;}

  private requirementText(r:Requirement|undefined){if(!r)return'条件已满足';const parts:string[]=[];for(const [k,v] of Object.entries(r.statsMin??{})){const key=k as StatKey;parts.push(`${this.runtime.base.ATTR[key]?.name??key} ≥ ${label(key,Number(v))}`);}for(const [k,v] of Object.entries(r.statsMax??{})){const key=k as StatKey;parts.push(`${this.runtime.base.ATTR[key]?.name??key} ≤ ${label(key,Number(v))}`);}if(r.tagsAll?.length)parts.push(`经历：${r.tagsAll.join(' / ')}`);if(r.tagsAny?.length)parts.push(`任一经历：${r.tagsAny.join(' / ')}`);if(r.wealthMin!=null)parts.push(`财富至少 ${money(r.wealthMin)}`);if(r.careerLevelMin!=null)parts.push(`职业至少 ${r.careerLevelMin} 阶`);if(r.traitsAll?.length)parts.push(`命格：${r.traitsAll.join(' / ')}`);if(r.synergiesAll?.length)parts.push(`羁绊：${r.synergiesAll.map(synergyName).join(' / ')}`);return parts.join(' · ')||'隐藏条件';}
  private responsePanel(s:Readonly<GameState>,c:ActionChoice,index:number){return`<div class="response-stage ${c.rare?'prismatic-stage':''}"><button class="back-event" data-action="close-response">← 返回年度事件</button><div class="response-head"><small>${esc(c.category)} · EVENT</small><h2>${esc(c.title)}</h2><p>${esc(c.desc)}</p></div><div class="responses">${(c.responses??[]).map((r,j)=>{const ok=passes(s,r.requires);return`<button data-action="response" data-index="${index}" data-response="${j}" ${!ok||s.ui.busy?'disabled':''} class="response ${ok?'available':'locked'}"><span>${ok?'可选择':'🔒 条件不足'}</span><strong>${esc(r.label)}</strong><p>${esc(r.desc??r.hint??'')}</p><em>${ok?esc(r.hint??'结果仍受运气与构筑影响'):esc(this.requirementText(r.requires))}</em></button>`}).join('')}</div></div>`;}
  private choices(s:Readonly<GameState>){if(this.openChoice!=null){const c=s.currentChoices[this.openChoice];if(c?.responses?.length)return`<section class="choice-wrap response-wrap">${this.responsePanel(s,c,this.openChoice)}</section>`;this.openChoice=null;}
    const zhou=s.age===1,fate=s.fate.targetAge===s.age&&!s.fate.triggered,rare=!zhou&&s.currentChoices.some(c=>c.rare);const mode=zhou?'zhou':fate?'fate':rare?'rare':'normal';const ritual=zhou?`<div class="zhou-ritual"><span>AGE ONE · FIRST CHOICE</span><h1>抓 周</h1><p>先选你伸手抓的东西。所有卡面保持中性，真正的稀有度要等结果发生后才揭晓。</p></div>`:fate?`<div class="event-ritual fate"><span>FATE NODE</span><strong>拉刻西斯节点 · 宿命奇点</strong><p>这一组选项会成为整条世界线的分叉点。</p></div>`:rare?`<div class="event-ritual prismatic"><span>PRISMATIC ENCOUNTER</span><strong>隐藏事件浮出水面</strong><p>它的出现本身已经很稀有，但真正的彩色结果仍然要靠你打出来。</p></div>`:'';
    return`<section class="choice-wrap event-${mode}">${ritual}<div class="section"><div><strong>${zhou?'挑一个你想抓的物件':fate?'选择你的世界线':'这一年，你把主要精力押在哪里？'}</strong><p>${zhou?'五张卡不提前告诉你哪张会天胡。':'事件卡只是“发生了什么”；有多个回答的事件点进去再做真正决策。'}</p></div><span>${s.currentChoices.length} 选 1</span></div><div class="choices">${s.currentChoices.map((c,i)=>`<button data-action="choice" data-index="${i}" ${s.ui.busy?'disabled':''} class="choice-card ${!zhou&&c.rare?'rare':''} ${c.sourceEvent==='lachesis'?'fate-choice':''}"><small class="choice-kicker"><span>${esc(c.category)}</span>${c.responses?.length?`<b>${c.responses.length} 个回答</b>`:c.sourceEvent==='lachesis'?'<b>命运</b>':!zhou&&c.rare?'<b>✦ 稀有</b>':''}</small><strong>${esc(c.title)}</strong><p>${esc(c.desc)}</p><em>${esc(c.hint??'结果会被经历、时代和构筑共同改写。')}</em></button>`).join('')}</div></section>`;}
  private nav(view:'game'|'info'|'collection'){return`<nav class="v8-nav"><button data-action="view" data-view="game" class="${view==='game'?'active':''}">🎮 人生</button><button data-action="view" data-view="info" class="${view==='info'?'active':''}">🧬 构筑</button><button data-action="view" data-view="collection" class="${view==='collection'?'active':''}">📚 图鉴</button></nav>`;}
  private game(){const s=this.runtime.store.get();if(s.age===1)return`<main class="shell game zhou-game">${this.hud(s)}${this.choices(s)}${this.stories(s)}${this.nav('game')}</main>`;return`<main class="shell game">${this.hud(s)}${this.finance(s)}${this.synergyStrip(s)}${this.states(s)}${this.world(s)}${this.stories(s)}${this.choices(s)}${this.nav('game')}</main>`;}

  private info(){const s=this.runtime.store.get(),route=this.runtime.base.CAREER_ROUTES.find(x=>x.id===s.careerRoute);return`<main class="shell info">${this.hud(s)}${this.synergyStrip(s)}
    <section class="panel build-panel"><div class="section"><div><strong>🧬 当前 Build</strong><p>命格、进化、羁绊和隐藏路线现在都会改规则，而不是只贴标签。</p></div><span>${s.synergies.length} 羁绊 · ${s.routesUnlocked.length} 路线</span></div><div class="synergy-grid">${s.synergies.length?s.synergies.map(y=>`<article><small>TIER ${y.tier}</small><strong>${esc(y.name)}</strong><p>${esc(y.desc)}</p></article>`).join(''):'<p>当前还没有形成明确羁绊。继续让同方向命格和经历咬合。</p>'}</div><div class="route-grid">${s.routesUnlocked.map(id=>{const d=routeDef(id);return d?`<article><small>HIDDEN ROUTE</small><strong>${esc(d.title)}</strong><p>${esc(d.desc)}</p></article>`:''}).join('')}</div></section>
    <section class="panel career-panel"><div class="section"><div><strong>🧳 职业路线</strong><p>职业是长期构筑，不是单次事件。</p></div><span>${route?`${s.careerLevel}/5 阶`:'尚未进入'}</span></div>${route?`<div class="ladder">${route.titles.map((x,i)=>`<div class="${i+1===s.careerLevel?'now':i+1<s.careerLevel?'done':''}"><b>${i+1}</b><span>${esc(x)}</span><small>${money(route.salaries[i]!)}/月</small></div>`).join('')}</div>`:'<p>毕业、转行和机会会把你带进一条职业路线。</p>'}</section>
    ${this.relationshipPanel(s)}
    <section class="panel trait-panel"><div class="section"><div><strong>🏷️ 命格词条</strong><p>进化后的命格会直接改名，并在轨迹里留下进化事件。</p></div><span>${s.traits.length} 个</span></div><div class="trait-card-grid trait-library">${s.traits.map(t=>this.traitCard(t)).join('')}</div></section>
    <section class="panel history-panel"><div class="section"><div><strong>📜 完整人生轨迹</strong><p>所有被系统记住的选择、人物与事故。</p></div><span>${s.history.length} 条</span></div><div class="history">${s.history.slice(0,180).map(h=>`<article class="${h.tone} rarity-${h.rarity??'normal'}"><b>${h.age} 岁 · ${esc(h.title)}</b><p>${esc(h.text)}</p></article>`).join('')}</div></section>
    <section class="panel save-panel"><div class="section"><div><strong>💾 存档与节奏</strong><p>${esc(s.ui.message||'自动保存开启')}</p></div><span>IndexedDB</span></div><div class="settings-actions"><button data-action="save">立即保存</button><button data-action="fast">⚡ 动画简化：${s.ui.fast?'开':'关'}</button></div></section>${this.nav('info')}</main>`;}
  private relationshipPanel(s:Readonly<GameState>){const list=[...s.relationships].sort((a,b)=>(b.role==='伴侣'?1000:0)+b.affinity*5+b.sharedEvents*8-((a.role==='伴侣'?1000:0)+a.affinity*5+a.sharedEvents*8));return`<section class="panel network"><div class="section"><div><strong>🕸️ 关系网</strong><p>普通人物不再反复占据四选一；只有重大关系节点才会升级为主事件。</p></div><span>在世 ${list.filter(x=>x.alive).length} · 已故 ${list.filter(x=>!x.alive).length}</span></div>${list.length?`<div class="rel-grid">${list.slice(0,12).map(r=>{const cr=this.runtime.base.CAREER_ROUTES.find(x=>x.id===r.careerRoute);return`<article class="rel ${roleClass(r)}"><div><div class="avatar">${this.runtime.avatarEmoji(r.avatar)}</div><strong>${esc(r.name)}</strong><b>${r.alive?r.role:'已故'}</b></div><span>${esc(r.gender)} · ${r.alive?`${Math.max(18,s.age-r.ageGap)}岁`:`享年${r.deathAge??'?'}岁`} · ${esc(cr?.titles[r.careerLevel-1]??'普通工作')}</span><small>相识于你${r.metAge}岁 · ${r.sharedEvents}次交集 · ${r.affinity>=70?'非常亲近':r.affinity>=35?'亲近':r.affinity>=0?'普通':r.affinity>-45?'紧张':'敌对'}</small><p>${esc(r.history[0]?.text??'这一年没有特别变化。')}</p></article>`}).join('')}</div>`:'<p>人物会从工作、生活和选择结果中自然进入关系网，而不是每年强行弹出来。</p>'}</section>`;}

  private collection(){const m=this.runtime.metaSnapshot(),defs=this.runtime.base.TRAITS as any[],discovered=defs.filter(x=>m.discoveredTraits.includes(x.id)),unknown=Math.max(0,defs.length-discovered.length);return`<main class="shell collection"><section class="collection-hero"><small>META PROGRESSION</small><h1>世界线图鉴</h1><p>不直接给下一局永久加属性；它记录你真正发现过什么，并偶尔留下前世回响。</p></section>
    <section class="metrics collection-metrics"><div><small>已完成世界线</small><strong>${m.runs}</strong></div><div><small>命格发现</small><strong>${discovered.length}/${defs.length}</strong></div><div><small>隐藏路线</small><strong>${m.discoveredRoutes.length}/${this.runtime.routeCatalog().length}</strong></div><div><small>特殊结局</small><strong>${m.endings.length}</strong></div></section>
    <section class="panel"><div class="section"><div><strong>🏷️ 已发现命格</strong><p>未发现内容保持 ???，给重开留下目标。</p></div><span>${unknown} 未发现</span></div><div class="trait-card-grid trait-library">${discovered.slice(0,80).map(d=>this.traitCard({id:d.id,name:d.name,rarity:d.rarity,desc:d.desc})).join('')}${unknown?`<article class="trait-card unknown"><div class="trait-rarity">UNKNOWN × ${unknown}</div><strong>???</strong><p>某些命格还没有出现在你的世界线里。</p></article>`:''}</div></section>
    <section class="panel"><div class="section"><div><strong>✦ 羁绊发现</strong><p>真正形成过的 Build 才会记录。</p></div><span>${m.discoveredSynergies.length}</span></div><div class="archive-tags">${m.discoveredSynergies.map(id=>`<span>${esc(synergyName(id))}</span>`).join('')||'<p>暂无发现</p>'}</div></section>
    <section class="panel"><div class="section"><div><strong>🗺️ 隐藏路线</strong><p>没走到的路线只给线索，不给完整攻略。</p></div><span>${m.discoveredRoutes.length}</span></div><div class="route-grid">${this.runtime.routeCatalog().map(r=>m.discoveredRoutes.includes(r.id)?`<article><small>DISCOVERED</small><strong>${esc(r.title)}</strong><p>${esc(r.desc)}</p></article>`:`<article class="locked-route"><small>???</small><strong>未发现路线</strong><p>${esc(r.clue)}</p></article>`).join('')}</div></section>
    <section class="panel"><div class="section"><div><strong>↻ 前世回响</strong><p>偶尔会在下一局早年变成一次很轻的直觉偏置。</p></div><span>${m.echoes.length}</span></div><div class="archive-tags">${m.echoes.map(x=>`<span>${esc(x)}</span>`).join('')||'<p>暂无回响</p>'}</div></section>${this.nav('collection')}</main>`;}

  private end(){const s=this.runtime.store.get(),after=this.runtime.relationships.afterlives(),rank=s.score>2300?'SSR':s.score>1850?'SS':s.score>1450?'S':s.score>1000?'A':'B',peak=s.financeHistory.reduce((m,x)=>Math.max(m,x.closing),s.wealthPeak),ending=this.runtime.ending(),key=s.history.filter(h=>h.kind==='rare'||h.kind==='evolution'||h.kind==='choice').slice(0,3),hints=this.runtime.missedRouteHints();return`<main class="shell ending"><section class="end-hero"><span>${rank}</span><div><small>SPECIAL ENDING</small><h1>${esc(ending.title)}</h1><p>${s.age} 岁 · ${esc(s.deathReason)} · 世界线 ${s.fate.worldline}</p><em>${esc(ending.desc)}</em></div></section><section class="metrics"><div><small>最终财富</small><strong>${money(s.wealth)}</strong></div><div><small>财富峰值</small><strong>${money(peak)}</strong></div><div><small>职业峰值</small><strong>${s.careerPeak}/5</strong></div><div><small>稀有事件</small><strong>${s.rareEvents}</strong></div></section>
    <section class="panel final-build"><div class="section"><div><strong>🧬 这一局最终 Build</strong><p>不是只给一个分数，而是告诉你这局到底成了什么。</p></div><span>${s.synergies.length} 羁绊</span></div><div class="archive-tags">${s.synergies.map(y=>`<span>${esc(y.name)} ×${y.tier}</span>`).join('')||'<span>没有形成稳定羁绊</span>'}</div><div class="trait-card-grid trait-library">${s.traits.slice(0,8).map(t=>this.traitCard(t)).join('')}</div></section>
    <section class="panel"><div class="section"><div><strong>🎬 最关键的三幕</strong><p>这几件事最能代表这条世界线。</p></div><span>${key.length}</span></div>${key.map(h=>`<article class="end-key"><b>${h.age} 岁 · ${esc(h.title)}</b><p>${esc(h.text)}</p></article>`).join('')||'<p>这一生没有留下足够鲜明的关键事件。</p>'}</section>
    ${hints.length?`<section class="panel missed"><div class="section"><div><strong>🔒 你差点摸到的路线</strong><p>不给完整答案，只留下一点“下一局可以试试”的线索。</p></div><span>NEXT RUN</span></div>${hints.map(x=>`<p>· ${esc(x)}</p>`).join('')}</section>`:''}
    ${s.fate.triggered&&s.fate.snapshotKey?`<section class="panel fate-end"><strong>✦ 拉刻西斯节点 · 宿命奇点</strong><p>${s.fate.targetAge} 岁，你选择了「${esc(s.fate.branch??'未知')}」。</p><button data-action="rewind">↶ 回到 ${s.fate.targetAge} 岁，走另一条人生</button></section>`:''}
    <section class="panel after"><div class="section"><div><strong>🕯️ 你死之后，他们继续活着</strong><p>少而深的人物关系，在终局继续留下余波。</p></div><span>${after.length} 人</span></div>${after.map(r=>`<article><b>${esc(r.name)} · ${esc(r.role)}</b><p>${esc((r as any).epilogue)}</p></article>`).join('')}</section><div class="end-actions"><button data-action="fresh">带着图鉴，再开一条世界线</button></div></main>`;}
}
