import fs from 'node:fs';import path from 'node:path';import {GameRuntime} from '../v7/dist/engine.js';
class FsContent{constructor(root){this.root=root;this._base=null;this.cache=new Map()}async base(){return this._base??=JSON.parse(fs.readFileSync(path.join(this.root,'base.json'),'utf8'))}async events(age){const stage=age<=12?'childhood':age<=22?'youth':age<=59?'adult':'senior';if(!this.cache.has(stage))this.cache.set(stage,JSON.parse(fs.readFileSync(path.join(this.root,`events-${stage}.json`),'utf8')));return this.cache.get(stage)}}
class FastPersistence{constructor(){this.snaps=new Map();this.meta=null}async save(){}async load(){return null}async putSnapshot(k,s){this.snaps.set(k,structuredClone(s))}async getSnapshot(k){const s=this.snaps.get(k);return s?structuredClone(s):null}async saveMeta(m){this.meta=structuredClone(m)}async loadMeta(){return this.meta?structuredClone(this.meta):null}}
const provider=new FsContent(path.join(process.cwd(),'v7/generated'));const base=await provider.base();if(base.CAREER_ROUTES.length!==50)throw new Error(`V8 expected 50 careers, got ${base.CAREER_ROUTES.length}`);if(base.TRAITS.length<150)throw new Error(`V8 trait pool too small ${base.TRAITS.length}`);
const q=(a,p)=>{const x=[...a].sort((a,b)=>a-b);return x[Math.floor((x.length-1)*p)]};const runs=Number(process.env.V7_RUNS||120),ages=[],wealths=[];let debt=0,partner=0,million=0,fate=0,noChoices=0,deadContacts=0,contacts=0,maxSteps=0,synergyRuns=0,routeRuns=0,evolutionRuns=0,zhouPrismatic=0,majorRelationshipEvents=0;
for(let i=0;i<runs;i++){const rt=new GameRuntime(provider,new FastPersistence());await rt.init(100000+i);const first=rt.store.get();if(first.wealth!==0)throw new Error(`infant wealth must start at zero, got ${first.wealth}`);if(first.currentChoices.length!==5||first.currentChoices.some(c=>c.rare)||first.currentChoices.some(c=>c.outcomes.length!==3))throw new Error('zhou ritual contract broken');if(first.traits.some(t=>!t.desc&&!t.effects&&!t.mods))throw new Error('trait hydration missing');let steps=0;while(rt.store.get().alive&&rt.store.get().age<112&&steps++<125){const s=rt.store.get();if(!s.currentChoices.length){noChoices++;await rt.ensureChoices();if(!rt.store.get().currentChoices.length)throw new Error(`no choices at age ${s.age}`)}const idx=(i+steps)%rt.store.get().currentChoices.length;await rt.resolve(idx);const st=rt.store.get();if(st.ledger){const sum=st.ledger.items.reduce((a,b)=>a+b.amount,0);if(Math.abs(sum-st.ledger.net)>1)throw new Error(`ledger mismatch run ${i}`);}}
 const s=rt.store.get();maxSteps=Math.max(maxSteps,steps);ages.push(s.age);wealths.push(s.wealth);if(s.wealth<0)debt++;if(s.partnerId||s.relationships.some(r=>r.role==='伴侣'))partner++;if(s.wealthPeak>=1_000_000)million++;if(s.fate.triggered)fate++;deadContacts+=s.relationships.filter(r=>!r.alive).length;contacts+=s.relationships.length;if(s.synergies.length)synergyRuns++;if(s.routesUnlocked.length)routeRuns++;if(s.traits.some(t=>(t.level??1)>1))evolutionRuns++;if(s.history.some(h=>h.sourceId==='zhou'&&h.rarity==='prismatic'))zhouPrismatic++;majorRelationshipEvents+=s.history.filter(h=>h.sourceId==='social_romance'||h.sourceId==='social_crisis').length;}
const report={version:'V8-on-V7-runtime',runs,medianAge:q(ages,.5),p90Age:q(ages,.9),age90plus:ages.filter(x=>x>=90).length/runs,debtRate:debt/runs,partnerRate:partner/runs,millionPeakRate:million/runs,fateRate:fate/runs,medianFinalWealth:q(wealths,.5),p10Wealth:q(wealths,.1),p90Wealth:q(wealths,.9),avgContacts:contacts/runs,avgDeadContacts:deadContacts/runs,synergyRate:synergyRuns/runs,routeRate:routeRuns/runs,evolutionRate:evolutionRuns/runs,zhouPrismaticRate:zhouPrismatic/runs,avgMajorRelationshipEvents:majorRelationshipEvents/runs,noChoices,maxSteps,generatedAt:new Date().toISOString()};
if(report.medianAge<60||report.medianAge>92)throw new Error(`lifespan drift ${report.medianAge}`);if(report.age90plus>.42)throw new Error(`90+ too common ${report.age90plus}`);if(report.debtRate>.55)throw new Error(`debt rate too high ${report.debtRate}`);if(report.millionPeakRate>.86)throw new Error(`wealth too easy ${report.millionPeakRate}`);if(report.fateRate<.82)throw new Error(`fate trigger too low ${report.fateRate}`);if(report.synergyRate<.55)throw new Error(`build synergies too rare ${report.synergyRate}`);if(report.avgContacts>9)throw new Error(`relationship graph flooding ${report.avgContacts}`);if(report.avgMajorRelationshipEvents>5)throw new Error(`major person events too frequent ${report.avgMajorRelationshipEvents}`);if(report.noChoices>0)throw new Error(`choice deadlocks ${report.noChoices}`);
{const p=new FastPersistence(),rt=new GameRuntime(provider,p);await rt.init(998877);if(rt.store.get().wealth!==0)throw new Error('fresh run infant wealth regression');await rt.resolve(0);if(!rt.store.get().history.length)throw new Error('zhou result missing from history');let foundResponses=false;for(let g=0;g<30&&rt.store.get().alive;g++){const st=rt.store.get();if(st.currentChoices.some(c=>c.responses?.length)){foundResponses=true;break}await rt.resolve(0)}if(!foundResponses)throw new Error('event responses never surfaced in 30 years');}
{const p=new FastPersistence(),rt=new GameRuntime(provider,p);await rt.init(998878);while(rt.store.get().age<rt.store.get().fate.targetAge){await rt.resolve(0)}if(!rt.store.get().fate.snapshotKey)await rt.ensureChoices();const target=rt.store.get().age;await rt.resolve(0);while(rt.store.get().alive&&rt.store.get().age<Math.min(80,target+12))await rt.resolve(0);if(rt.store.get().alive)rt.store.dispatch({type:'DIE',reason:'回归测试'});const wl=rt.store.get().fate.worldline;if(!(await rt.rewindFate()))throw new Error('fate rewind failed');if(rt.store.get().age!==target||rt.store.get().fate.worldline!==wl+1||rt.store.get().currentChoices.length!==4)throw new Error('fate rewind state invalid');}
fs.writeFileSync(path.join(process.cwd(),'v7/generated/sim-report.json'),JSON.stringify(report,null,2));console.log('V8 simulation passed',report);
